---
permalink: protect-scsql/concept_how_long_to_retain_transaction_log_backups_on_the_source_storage_system.html 
sidebar: sidebar 
keywords: retain transaction log backups 
summary: El complemento SnapCenter para Microsoft SQL Server necesita copias de seguridad del registro de transacciones para realizar operaciones de restauración actualizadas, que restauran su base de datos a un tiempo entre dos copias de seguridad completas. 
---
= ¿Durante cuánto tiempo se deben conservar las copias de seguridad del registro de transacciones en el sistema de almacenamiento de origen?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El complemento SnapCenter para Microsoft SQL Server necesita copias de seguridad del registro de transacciones para realizar operaciones de restauración actualizadas, que restauran su base de datos a un tiempo entre dos copias de seguridad completas.

Por ejemplo, si Plug-in para SQL Server realizó una copia de seguridad completa a las 8:00 a. m. y otra copia de seguridad completa a las 5:00 p. m., podría usar la última copia de seguridad del registro de transacciones para restaurar la base de datos a cualquier momento entre las 8:00 a. m. y las 5:00 p. m. Si los registros de transacciones no están disponibles, Plug-in para SQL Server solo puede realizar operaciones de restauración en un punto en el tiempo, que restauran una base de datos al momento en que Plug-in para SQL Server completó una copia de seguridad completa.

Por lo general, se necesitan operaciones de restauración actualizadas solo por uno o dos días.  De forma predeterminada, SnapCenter conserva un mínimo de dos días.
