---
permalink: protect-scsql/concept_prerequisites_for_using_snapcenter_plug_in_for_microsoft_sql_server.html 
sidebar: sidebar 
keywords: credential 
summary: Antes de comenzar a utilizar el complemento para SQL Server, el administrador de SnapCenter debe instalar y configurar SnapCenter Server y realizar las tareas previas requeridas. 
---
= Requisitos previos para utilizar el complemento de SnapCenter para Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de comenzar a utilizar el complemento para SQL Server, el administrador de SnapCenter debe instalar y configurar SnapCenter Server y realizar las tareas previas requeridas.

* Instalar y configurar SnapCenter Server.
* Inicie sesión en SnapCenter.
* Configure el entorno de SnapCenter agregando o asignando conexiones del sistema de almacenamiento y creando credenciales.
+

NOTE: SnapCenter no admite varias SVM con el mismo nombre en diferentes clústeres.  Cada SVM compatible con SnapCenter debe tener un nombre único.

* Agregue hosts, instale los complementos, descubra (actualice) los recursos y configure los complementos.
* Mueva una base de datos existente de Microsoft SQL Server desde un disco local a un LUN de NetApp o viceversa ejecutando Invoke-SmConfigureResources.
+
Para obtener información sobre cómo ejecutar el cmdlet, consulte la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets del software SnapCenter"]

* Si utiliza SnapCenter Server para proteger bases de datos SQL que residen en LUN o VMDK de VMware RDM, debe implementar el SnapCenter Plug-in for VMware vSphere y registrar el complemento con SnapCenter.  La documentación del SnapCenter Plug-in for VMware vSphere tiene más información.
+
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["Documentación del SnapCenter Plug-in for VMware vSphere"]

* Realice el aprovisionamiento de almacenamiento del lado del host mediante el complemento SnapCenter para Microsoft Windows.
* Configure las relaciones de SnapMirror y SnapVault, si desea una replicación del backup.


Para obtener más detalles, consulte la información de instalación de SnapCenter .

Para los usuarios de SnapCenter 4.1.1, la documentación del SnapCenter Plug-in for VMware vSphere 4.1.1 tiene información sobre cómo proteger bases de datos y sistemas de archivos virtualizados.  Para los usuarios de SnapCenter 4.2.x, NetApp Data Broker 1.0 y 1.0.1, la documentación tiene información sobre cómo proteger bases de datos y sistemas de archivos virtualizados mediante el SnapCenter Plug-in for VMware vSphere que proporciona el dispositivo virtual NetApp Data Broker basado en Linux (formato Open Virtual Appliance).  Para los usuarios de SnapCenter 4.3.x, la documentación del SnapCenter Plug-in for VMware vSphere 4.3 tiene información sobre cómo proteger bases de datos y sistemas de archivos virtualizados mediante el dispositivo virtual basado en Linux del SnapCenter Plug-in for VMware vSphere (formato Open Virtual Appliance).

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["Documentación del SnapCenter Plug-in for VMware vSphere"]
