---
permalink: protect-scsql/concept_snapcenter_plug_in_for_microsoft_sql_server_features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: El complemento para SQL Server se integra con Microsoft SQL Server en el host de Windows y con la tecnología NetApp Snapshot en el sistema de almacenamiento.  Para trabajar con el complemento para SQL Server, utilice la interfaz de SnapCenter . 
---
= Funciones del complemento SnapCenter para Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El complemento para SQL Server se integra con Microsoft SQL Server en el host de Windows y con la tecnología NetApp Snapshot en el sistema de almacenamiento.  Para trabajar con el complemento para SQL Server, utilice la interfaz de SnapCenter .

El complemento para SQL Server incluye estas características principales:

* *Interfaz gráfica de usuario unificada impulsada por SnapCenter*
+
La interfaz de SnapCenter le proporciona estandarización y consistencia entre complementos y entornos.  La interfaz de SnapCenter le permite completar procesos de copia de seguridad y restauración consistentes en todos los complementos, utilizar informes centralizados, usar vistas de panel de un vistazo, configurar el control de acceso basado en roles (RBAC) y monitorear trabajos en todos los complementos.  SnapCenter también ofrece programación centralizada y gestión de políticas para respaldar operaciones de copia de seguridad y clonación.

* *Administración central automatizada*
+
Puede programar copias de seguridad rutinarias de SQL Server, configurar la retención de copias de seguridad basada en políticas y configurar operaciones de restauración en un punto en el tiempo y actualizadas al minuto.  También puede supervisar de forma proactiva su entorno de SQL Server configurando SnapCenter para enviar alertas por correo electrónico.

* *Tecnología NetApp Snapshot sin interrupciones*
+
El complemento para SQL Server utiliza la tecnología NetApp Snapshot con el complemento NetApp SnapCenter para Microsoft Windows.  Esto le permite realizar copias de seguridad de bases de datos en segundos y restaurarlas rápidamente sin desconectar SQL Server.  Las instantáneas consumen un espacio de almacenamiento mínimo.



Además de estas características principales, el complemento para SQL Server ofrece los siguientes beneficios:

* Soporte para flujos de trabajo de copia de seguridad, restauración, clonación y verificación
* Seguridad respaldada por RBAC y delegación de roles centralizada
* Creación de copias puntuales y con uso eficiente del espacio de bases de datos de producción para pruebas o extracción de datos mediante la tecnología NetApp FlexClone
+
Se requiere una licencia FlexClone en el sistema de almacenamiento que contiene el clon.

* Verificación de copias de seguridad automatizada y sin interrupciones
* Capacidad de ejecutar múltiples copias de seguridad al mismo tiempo en varios servidores
* Cmdlets de PowerShell para la creación de scripts de operaciones de copia de seguridad, verificación, restauración y clonación
* Compatibilidad con grupos de disponibilidad AlwaysOn (AG) en SQL Server para acelerar las operaciones de configuración, copia de seguridad y restauración de AG
* Base de datos en memoria y extensión de grupo de búfer (BPE) como parte de SQL Server 2014
* Soporte para copias de seguridad de LUN y discos de máquinas virtuales (VMDK)
* Soporte para infraestructuras físicas y virtualizadas
* Compatibilidad con iSCSI, Fibre Channel, FCoE, mapeo de dispositivos sin procesar (RDM) y VMDK sobre NFS y VMFS
+

NOTE: Los volúmenes NAS deben tener una política de exportación predeterminada en la máquina virtual de almacenamiento (SVM).

* Compatibilidad con FileStream y grupos de archivos en bases de datos independientes de SQL Server.
* Compatibilidad con memoria no volátil express (NVMe) en Windows Server 2022
+
** Flujos de trabajo de copia de seguridad, restauración, clonación y verificación en el diseño VMDK creado en NVMe a través de TCP/IP.
** Admite la versión de firmware NVMe 1.3 a partir de la actualización 2 de ESX 8.0 y requiere la versión de hardware virtual 21.
** El clúster de conmutación por error de Windows Server (WSFC) no es compatible con aplicaciones a través de VMDK en NVMe sobre TCP/IP.


* Admite la sincronización activa de SnapMirror (lanzada inicialmente como SnapMirror Business Continuity [SM-BC]) que permite que los servicios comerciales sigan funcionando incluso en caso de una falla total del sitio, permitiendo que las aplicaciones conmuten por error de manera transparente mediante una copia secundaria.  No se requiere intervención manual ni secuencias de comandos adicionales para activar una conmutación por error con la sincronización activa de SnapMirror .

