---
permalink: protect-scsql/concept_requirements_for_restoring_a_database.html 
sidebar: sidebar 
keywords: Requirements 
summary: Antes de restaurar una base de datos de SQL Server desde una copia de seguridad del complemento de SnapCenter para Microsoft SQL Server, debe asegurarse de que se cumplan varios requisitos. 
---
= Requisitos para restaurar una base de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de restaurar una base de datos de SQL Server desde una copia de seguridad del complemento de SnapCenter para Microsoft SQL Server, debe asegurarse de que se cumplan varios requisitos.

* La instancia de SQL Server de destino debe estar en línea y en ejecución antes de poder restaurar una base de datos.
+
Esto se aplica tanto a las operaciones de restauración de la base de datos del usuario como a las operaciones de restauración de la base de datos del sistema.

* Las operaciones de SnapCenter que están programadas para ejecutarse en los datos de SQL Server que está restaurando deben estar deshabilitadas, incluidos todos los trabajos programados en servidores de administración remota o de verificación remota.
* Si las bases de datos del sistema no funcionan, primero debe reconstruirlas utilizando una utilidad de SQL Server.
* Si está instalando el complemento, asegúrese de otorgar permisos para que otras funciones puedan restaurar las copias de seguridad del grupo de disponibilidad (AG).
+
La restauración de AG falla cuando se cumple una de las siguientes condiciones:

+
** Si el complemento lo instala el usuario RBAC y un administrador intenta restaurar una copia de seguridad de AG
** Si un administrador instala el complemento y un usuario RBAC intenta restaurar una copia de seguridad de AG


* Si está restaurando copias de seguridad del directorio de registro personalizado en un host alternativo, el servidor SnapCenter y el host del complemento deben tener la misma versión de SnapCenter instalada.
* Debe tener instalado el hotfix de Microsoft, KB2887595.  El sitio de soporte de Microsoft contiene más información sobre KB2887595.
+
https://support.microsoft.com/kb/2887595["Artículo de soporte técnico de Microsoft 2887595: Paquete acumulativo de actualizaciones de Windows RT 8.1, Windows 8.1 y Windows Server 2012 R2: noviembre de 2013"]

* Debes haber realizado una copia de seguridad de los grupos de recursos o de la base de datos.
* Si está replicando instantáneas a un espejo o bóveda, el administrador de SnapCenter debe haberle asignado las máquinas virtuales de almacenamiento (SVM) tanto para los volúmenes de origen como para los volúmenes de destino.
+
Para obtener información sobre cómo los administradores asignan recursos a los usuarios, consulte la información de instalación de SnapCenter .

* Todos los trabajos de copia de seguridad y clonación deben detenerse antes de restaurar la base de datos.
* La operación de restauración puede expirar si el tamaño de la base de datos está en terabytes (TB).
+
Debe aumentar el valor del parámetro RESTTimeout de SnapCenter Server a 20000000 ms ejecutando el siguiente comando: Set-SmConfigSettings -Agent -configSettings @{"RESTTimeout" = "20000000"}.  Según el tamaño de la base de datos, el valor de tiempo de espera se puede cambiar y el valor máximo que se puede establecer es 86400000 ms.



Si desea restaurar mientras las bases de datos están en línea, la opción de restauración en línea debe estar habilitada en la página Restaurar.
