---
permalink: protect-scsql/task_install_the_snapcenter_plug_in_for_sql_server_silently.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: Debe instalar el complemento de SnapCenter para Microsoft SQL Server desde la interfaz de usuario de SnapCenter .  Sin embargo, si por algún motivo no puede, puede ejecutar el programa de instalación del complemento para SQL Server sin supervisión en modo silencioso desde la línea de comandos de Windows. 
---
= Instale el complemento de SnapCenter para Microsoft SQL Server de forma silenciosa desde la línea de comandos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe instalar el complemento de SnapCenter para Microsoft SQL Server desde la interfaz de usuario de SnapCenter .  Sin embargo, si por algún motivo no puede, puede ejecutar el programa de instalación del complemento para SQL Server sin supervisión en modo silencioso desde la línea de comandos de Windows.

.Antes de empezar
* Debe eliminar la versión anterior del complemento SnapCenter para Microsoft SQL Server antes de instalarlo.
+
Para obtener más información, consulte  https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host["Cómo instalar un complemento de SnapCenter de forma manual y directa desde el host del complemento"^] .



.Pasos
. Valide si la carpeta C:\temp existe en el host del complemento y si el usuario que inició sesión tiene acceso completo a ella.
. Descargue el complemento para el software SQL Server desde C:\ProgramData\ NetApp\ SnapCenter\Package Repository.
+
Se puede acceder a esta ruta desde el host donde está instalado el servidor SnapCenter .

. Copie el archivo de instalación en el host en el que desea instalar el complemento.
. Desde un símbolo del sistema de Windows en el host local, navegue hasta el directorio donde guardó los archivos de instalación del complemento.
. Instalar el complemento para el software SQL Server:
+
`"snapcenter_windows_host_plugin.exe"/silent /debuglog"Debug_Log_Path" /log"Log_Path" BI_SNAPCENTER_PORT=Num SUITE_INSTALLDIR="Install_Directory_Path" BI_SERVICEACCOUNT=domain\\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW,SCSQL`

+
Reemplace los valores de marcador de posición con sus datos

+
** Debug_Log_Path es el nombre y la ubicación del archivo de registro del instalador de la suite.
** Log_Path es la ubicación de los registros de instalación de los componentes del complemento (SCW, SCSQL y SMCore).
** Num es el puerto en el que SnapCenter se comunica con SMCore
** Install_Directory_Path es el directorio de instalación del paquete del complemento del host.
** domain\administrator es la cuenta de servicio web del complemento SnapCenter para Microsoft Windows.
** contraseña es la contraseña para la cuenta de servicio web del complemento SnapCenter para Microsoft Windows. + 
`"snapcenter_windows_host_plugin.exe"/silent /debuglog"C:\HPPW_SCSQL_Install.log" /log"C:\" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C:\Program Files\NetApp\SnapCenter" BI_SERVICEACCOUNT=domain\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW,SCSQL`


+

NOTE: Todos los parámetros pasados durante la instalación del complemento para SQL Server distinguen entre mayúsculas y minúsculas.

. Supervise el programador de tareas de Windows, el archivo de registro de instalación principal C:\Installdebug.log y los archivos de instalación adicionales en C:\Temp.
. Supervise el directorio %temp% para verificar que los instaladores msiexe.exe estén instalando el software sin errores.
+

NOTE: La instalación del complemento para SQL Server registra el complemento en el host y no en el servidor SnapCenter .  Puede registrar el complemento en el servidor SnapCenter agregando el host mediante la GUI de SnapCenter o el cmdlet de PowerShell.  Una vez agregado el host, el complemento se descubre automáticamente.


