---
permalink: protect-scsql/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_sql.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Debe crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar los cmdlets de PowerShell para realizar operaciones de protección de datos.' 
---
= Cree una conexión al sistema de almacenamiento y una credencial mediante cmdlets de PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar los cmdlets de PowerShell para realizar operaciones de protección de datos.

.Antes de empezar
* Debería haber preparado el entorno de PowerShell para ejecutar los cmdlets de PowerShell.
* Debe tener los permisos necesarios en el rol de administrador de infraestructura para crear conexiones de almacenamiento.
* Debe asegurarse de que las instalaciones del complemento no estén en curso.
+
Las instalaciones de complementos de host no deben estar en progreso mientras se agrega una conexión al sistema de almacenamiento porque es posible que la memoria caché del host no se actualice y el estado de las bases de datos puede mostrarse en la GUI de SnapCenter como "`No disponible para respaldo`" o "`No en almacenamiento de NetApp ".

* Los nombres de los sistemas de almacenamiento deben ser únicos.
+
SnapCenter no admite varios sistemas de almacenamiento con el mismo nombre en diferentes clústeres.  Cada sistema de almacenamiento compatible con SnapCenter debe tener un nombre único y una dirección IP LIF de administración única.



.Pasos
. Inicie una sesión de conexión de PowerShell Core mediante el cmdlet Open-SmConnection.
+
Este ejemplo abre una sesión de PowerShell:

+
[listing]
----
PS C:\> Open-SmConnection
----
. Cree una nueva conexión al sistema de almacenamiento mediante el cmdlet Add-SmStorageConnection.
+
Este ejemplo crea una nueva conexión al sistema de almacenamiento:

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Cree una nueva credencial mediante el cmdlet Add-SmCredential.
+
Este ejemplo crea una nueva credencial llamada FinanceAdmin con credenciales de Windows:

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


La información sobre los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help command_name_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets del software SnapCenter"^] .
