---
permalink: protect-scsql/task-install-snapcenter-server-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: Proporciona instrucciones para instalar SnapCenter Server para Microsoft SQL Server. 
---
= Instalar SnapCenter Server para Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Proporciona un conjunto condensado de instrucciones de instalación para instalar SnapCenter Server para Microsoft SQL Server.



== Paso 1: Descargue e instale SnapCenter Server

. Descargue el paquete de instalación de SnapCenter Server desde https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["Sitio de soporte de NetApp"^] y luego haga doble clic en el exe.
+
Después de iniciar la instalación, se realizan todas las comprobaciones previas y, si no se cumplen los requisitos mínimos, se muestran mensajes de error o advertencia correspondientes.  Puede ignorar los mensajes de advertencia y continuar con la instalación; sin embargo, los errores deberían solucionarse.

. Revise los valores previamente completados necesarios para la instalación de SnapCenter Server y modifíquelos si es necesario.
+
No es necesario especificar la contraseña para la base de datos del repositorio del servidor MySQL.  Durante la instalación de SnapCenter Server, la contraseña se genera automáticamente.

+

NOTE: El carácter especial “%” no es compatible con la ruta personalizada para la instalación.  Si incluye “%” en la ruta, la instalación fallará.

. Haga clic en *Instalar ahora*.




== Paso 2: Inicia sesión en SnapCenter

. Inicie SnapCenter desde un acceso directo en el escritorio del host o desde la URL proporcionada por la instalación (_\https://server:8146_ para el puerto predeterminado 8146 donde está instalado SnapCenter Server).
. Introduzca las credenciales.
+
Para un formato de nombre de usuario de administrador de dominio integrado, utilice: _NetBIOS\<nombre de usuario>_ o _<nombre de usuario>@<dominio>_ o _<DomainFQDN>\<nombre de usuario>_.

+
Para un formato de nombre de usuario de administrador local integrado, utilice _<nombre de usuario>_.

. Haga clic en *Iniciar sesión*.




== Paso 3: Agregar una licencia basada en controlador de SnapCenter Standard

. Inicie sesión en el controlador utilizando la línea de comando ONTAP e ingrese:
+
`system license add -license-code <license_key>`

. Verificar la licencia:
+
`license show`





== Paso 4: Configurar las conexiones del sistema de almacenamiento

. En el panel izquierdo, haga clic en *Sistemas de almacenamiento > Nuevo*.
. En la página Agregar sistema de almacenamiento, realice lo siguiente:
+
.. Introduzca el nombre o la dirección IP del sistema de almacenamiento.
.. Introduzca las credenciales que se utilizan para acceder al sistema de almacenamiento.
.. Seleccione las casillas de verificación para habilitar el Sistema de gestión de eventos (EMS) y AutoSupport.


. Haga clic en *Más opciones* si desea modificar los valores predeterminados asignados a la plataforma, el protocolo, el puerto y el tiempo de espera.
. Haga clic en *Enviar*.

