---
permalink: protect-scsql/task_configure_CA_certificate_with_Windows_host_plug-in_services.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Configurar el certificado de CA con los servicios del complemento de host de Windows 
---
= Configurar el certificado de CA con los servicios del complemento de host de Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar el certificado CA con los servicios del complemento de host de Windows para activar el certificado digital instalado.

Realice los siguientes pasos en el servidor SnapCenter y en todos los hosts de complementos donde ya están implementados los certificados de CA.

.Pasos
. Elimine la vinculación del certificado existente con el puerto predeterminado 8145 de SMCore, ejecutando el siguiente comando:
+
`> netsh http delete sslcert ipport=0.0.0.0:_<SMCore Port>`

+
Por ejemplo:

+
 > netsh http delete sslcert ipport=0.0.0.0:8145
. Vincule el certificado recién instalado con los servicios del complemento de host de Windows, ejecutando los siguientes comandos:
+
....
> $cert = “_<certificate thumbprint>_”
> $guid = [guid]::NewGuid().ToString("B")
> netsh http add sslcert ipport=0.0.0.0: _<SMCore Port>_ certhash=$cert appid="$guid"
....
+
Por ejemplo:

+
....
> $cert = “a909502dd82ae41433e6f83886b00d4277a32a7b”
> $guid = [guid]::NewGuid().ToString("B")
> netsh http add sslcert ipport=0.0.0.0: _<SMCore Port>_ certhash=$cert appid="$guid"
....

