---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter utiliza credenciales para autenticar a los usuarios para las operaciones de SnapCenter .  Debe crear credenciales para instalar complementos de SnapCenter y credenciales adicionales para realizar operaciones de protección de datos en bases de datos o sistemas de archivos de Windows. 
---
= Configurar credenciales para el paquete de complementos de SnapCenter para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utiliza credenciales para autenticar a los usuarios para las operaciones de SnapCenter .  Debe crear credenciales para instalar complementos de SnapCenter y credenciales adicionales para realizar operaciones de protección de datos en bases de datos o sistemas de archivos de Windows.

.Antes de empezar
* Debe configurar las credenciales de Windows antes de instalar complementos.
* Debe configurar las credenciales con privilegios de administrador, incluidos derechos de administrador en el host remoto.
* Autenticación SQL en hosts de Windows
+
Debe configurar las credenciales de SQL después de instalar los complementos.

+
Si está implementando el complemento de SnapCenter para Microsoft SQL Server, debe configurar las credenciales de SQL después de instalar los complementos.  Configurar una credencial para un usuario con permisos de administrador de sistemas de SQL Server.

+
El método de autenticación SQL se autentica contra una instancia de SQL Server.  Esto significa que se debe descubrir una instancia de SQL Server en SnapCenter.  Por lo tanto, antes de agregar una credencial SQL, debe agregar un host, instalar paquetes de complementos y actualizar los recursos.  Necesita la autenticación de SQL Server para realizar operaciones como programar o descubrir recursos.



.Pasos
. En el panel de navegación izquierdo, haga clic en *Configuración*.
. En la página de Configuración, haga clic en *Credencial*.
. Haga clic en *Nuevo*.
. En la página Credencial, especifique la información necesaria para configurar las credenciales:
+
|===
| Para este campo... | Haz esto... 


 a| 
Nombre de la credencial
 a| 
Introduzca un nombre para la credencial.



 a| 
Nombre de usuario/Contraseña
 a| 
Introduzca el nombre de usuario y la contraseña que se utilizarán para la autenticación.

** Administrador de dominio
+
Especifique el administrador del dominio en el sistema donde va a instalar el complemento de SnapCenter . Los formatos válidos para el campo Nombre de usuario son:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrador local (sólo para grupos de trabajo)
+
Para los sistemas que pertenecen a un grupo de trabajo, especifique el administrador local integrado en el sistema donde va a instalar el complemento de SnapCenter . Puede especificar una cuenta de usuario local que pertenezca al grupo de administradores locales si esta cuenta tiene privilegios elevados o si la función de control de acceso de usuario está deshabilitada en el sistema host.  El formato válido para el campo Nombre de usuario es: `UserName`

+
No utilice comillas dobles (") ni tildes invertidas (`) en las contraseñas.  No debe utilizar los símbolos menor que (<) y exclamación (!) juntos en las contraseñas.  Por ejemplo, menos que<!10, menos que10<!, acento grave`12.





 a| 
Modo de autenticación
 a| 
Seleccione el modo de autenticación que desea utilizar.  Si selecciona el modo de autenticación SQL, también debe especificar la instancia del servidor SQL y el host donde se encuentra la instancia SQL.

|===
. Haga clic en *Aceptar*.


Una vez que termine de configurar las credenciales, es posible que desee asignar el mantenimiento de credenciales a un usuario o grupo de usuarios en la página Usuario y acceso.
