---
permalink: protect-sco/catalog-backups.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: Cómo SnapCenter descubre bases de datos de Oracle. 
---
= Cómo catalogar copias de seguridad con Oracle Recovery Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede catalogar las copias de seguridad de las bases de datos Oracle utilizando Oracle Recovery Manager (RMAN) para almacenar la información de copia de seguridad en el repositorio Oracle RMAN.

Las copias de seguridad catalogadas se pueden utilizar más adelante para operaciones de restauración a nivel de bloque o de recuperación de puntos en el tiempo del espacio de tabla.  Cuando no necesite estas copias de seguridad catalogadas, puede eliminar la información del catálogo.

La base de datos debe estar montada o en un estado superior para poder catalogar.  Puede realizar la catalogación de copias de seguridad de datos, copias de seguridad de registros de archivo y copias de seguridad completas.  Si la catalogación está habilitada para una copia de seguridad de un grupo de recursos que tiene varias bases de datos, la catalogación se realiza para cada base de datos.  Para las bases de datos Oracle RAC, la catalogación se realizará en el nodo preferido donde la base de datos esté al menos en estado montado.

Si desea catalogar copias de seguridad de una base de datos RAC, asegúrese de que no haya ningún otro trabajo en ejecución para esa base de datos.  Si se está ejecutando otro trabajo, la operación de catalogación falla en lugar de ponerse en cola.



== Base de datos de catálogo externo

De forma predeterminada, se utiliza el archivo de control de la base de datos de destino para la catalogación.  Si desea agregar una base de datos de catálogo externa, puede configurarla especificando la credencial y el nombre del sustrato de red transparente (TNS) del catálogo externo mediante el asistente de configuración de base de datos desde la interfaz gráfica de usuario (GUI) de SnapCenter .  También puede configurar la base de datos del catálogo externo desde la CLI ejecutando el comando Configure-SmOracleDatabase con las opciones -OracleRmanCatalogCredentialName y -OracleRmanCatalogTnsName.



== Comando RMAN

Si habilitó la opción de catalogación al crear una política de respaldo de Oracle desde la GUI de SnapCenter , los respaldos se catalogan utilizando Oracle RMAN como parte de la operación de respaldo.  También puede realizar una catalogación diferida de copias de seguridad ejecutando el `Catalog-SmBackupWithOracleRMAN` dominio.

Después de catalogar las copias de seguridad, puede ejecutar el `Get-SmBackupDetails` comando para obtener la información de respaldo catalogada, como la etiqueta de los archivos de datos catalogados, la ruta del catálogo de archivos de control y las ubicaciones de los registros de archivo catalogados.



== Formato de nombres

Si el nombre del grupo de discos ASM es mayor o igual a 16 caracteres, a partir de SnapCenter 3.0, el formato de nombre utilizado para la copia de seguridad es SC_HASHCODEofDISKGROUP_DBSID_BACKUPID.  Sin embargo, si el nombre del grupo de discos tiene menos de 16 caracteres, el formato de nombre utilizado para la copia de seguridad es DISKGROUPNAME_DBSID_BACKUPID, que es el mismo formato utilizado en SnapCenter 2.0.

El HASHCODEofDISKGROUP es un número generado automáticamente (de 2 a 10 dígitos) único para cada grupo de discos ASM.



== Operaciones de verificación cruzada

Puede realizar comprobaciones cruzadas para actualizar información obsoleta del repositorio RMAN sobre las copias de seguridad cuyos registros del repositorio no coinciden con su estado físico.  Por ejemplo, si un usuario elimina registros archivados del disco con un comando del sistema operativo, el archivo de control aún indica que los registros están en el disco, cuando en realidad no es así.

La operación de verificación cruzada le permite actualizar el archivo de control con la información.  Puede habilitar la verificación cruzada ejecutando el comando Set-SmConfigSettings y asignando el valor TRUE al parámetro ENABLE_CROSSCHECK.  El valor predeterminado se establece en FALSO.

`sccli Set-SmConfigSettings-ConfigSettingsTypePlugin-PluginCodeSCO-ConfigSettings "KEY=ENABLE_CROSSCHECK, VALUE=TRUE"`



== Eliminar información del catálogo

Puede eliminar la información del catálogo ejecutando el comando Uncatalog-SmBackupWithOracleRMAN.  No es posible eliminar la información del catálogo mediante la GUI de SnapCenter .  Sin embargo, la información de una copia de seguridad catalogada se elimina al eliminar la copia de seguridad o al eliminar el grupo de retención y recursos asociados con esa copia de seguridad catalogada.


NOTE: Cuando se fuerza la eliminación del host de SnapCenter , la información de las copias de seguridad catalogadas asociadas con ese host no se elimina.  Debe eliminar la información de todas las copias de seguridad catalogadas para ese host antes de forzar la eliminación del host.

Si la catalogación y descatalogación falla porque el tiempo de operación excedió el valor de tiempo de espera especificado para el parámetro ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT, debe modificar el valor del parámetro ejecutando el siguiente comando:

`/opt/Netapp/snapcenter/spl/bin/sccli Set-SmConfigSettings-ConfigSettingsType Plugin -PluginCode SCO-ConfigSettings "KEY=ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT,VALUE=user_defined_value"`

Después de modificar el valor del parámetro, reinicie el servicio SnapCenter Plug-in Loader (SPL) ejecutando el siguiente comando:

`/opt/NetApp/snapcenter/spl/bin/spl restart`

La información sobre los parámetros que se pueden utilizar con el comando y sus descripciones se puede obtener ejecutando Get-Help command_name. Alternativamente, puede consultar la https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["Guía de referencia de comandos del software SnapCenter"^] .
