---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-backup.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, backup, policy 
summary: SnapCenter le permite utilizar las variables de entorno predefinidas cuando ejecuta prescript y postscript mientras crea políticas de respaldo. 
---
= Variables de entorno predefinidas para prescript y postscript específicos de copia de seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter le permite utilizar las variables de entorno predefinidas cuando ejecuta prescript y postscript mientras crea políticas de respaldo.  Esta funcionalidad es compatible con todas las configuraciones de Oracle excepto VMDK.

SnapCenter predefine los valores de los parámetros que serán directamente accesibles en el entorno donde se ejecutan los scripts de shell.  No es necesario especificar manualmente los valores de estos parámetros al ejecutar los scripts.



== Variables de entorno predefinidas compatibles para crear una política de respaldo

* *SC_JOB_ID* especifica el ID del trabajo de la operación.
+
Ejemplo: 256

* *SC_ORACLE_SID* especifica el identificador del sistema de la base de datos.
+
Si la operación involucra múltiples bases de datos, el parámetro contendrá los nombres de las bases de datos separados por barras verticales.

+
Este parámetro se completará para los volúmenes de la aplicación.

+
Ejemplo: NFSB32|NFSB31

* *SC_HOST* especifica el nombre de host de la base de datos.
+
Para RAC, el nombre de host será el nombre del host en el que se realiza la copia de seguridad.

+
Este parámetro se completará para los volúmenes de la aplicación.

+
Ejemplo: scsmohost2.gdl.englabe.netapp.com

* *SC_OS_USER* especifica el propietario del sistema operativo de la base de datos.
+
Los datos se formatearán como <db1>@<osuser1>|<db2>@<osuser2>.

+
Ejemplo: NFSB31@oracle|NFSB32@oracle

* *SC_OS_GROUP* especifica el grupo del sistema operativo de la base de datos.
+
Los datos se formatearán como <db1>@<osgroup1>|<db2>@<osgroup2>.

+
Ejemplo: NFSB31@install|NFSB32@oinstall

* *SC_BACKUP_TYPE*" especifica el tipo de copia de seguridad (completa en línea, datos en línea, registro en línea, apagado sin conexión, montaje sin conexión)
+
Ejemplos:

+
** Para una copia de seguridad completa: ONLINEFULL
** copia de seguridad de solo datos: ONLINEDATA
** Solo para copia de seguridad de registros: ONLINELOG


* *SC_BACKUP_NAME* especifica el nombre de la copia de seguridad.
+
Este parámetro se completará para los volúmenes de la aplicación.

+
Ejemplo: DATOS@RG2_scspr2417819002_20-07-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_20-07-2021_12.16.48.9267_1|AV@RG2_scspr2417819002_20-07-2021_12.16.48.9267

* *SC_BACKUP_ID* especifica el ID de la copia de seguridad.
+
Este parámetro se completará para los volúmenes de la aplicación.

+
Ejemplo: DATOS@203|LOG@205|AV@207

* *SC_ORACLE_HOME* especifica la ruta del directorio de inicio de Oracle.
+
Ejemplo: NFSB32@/ora01/app/oracle/product/18.1.0/db_1|NFSB31@/ora01/app/oracle/product/18.1.0/db_1

* *SC_BACKUP_RETENTION* especifica el período de retención definido en la política.
+
Ejemplos:

+
** Para una copia de seguridad completa: Cada hora | DATOS @ DÍAS: 3 | REGISTRO @ RECUENTO: 4
** Solo para copias de seguridad de datos bajo demanda: Ondemand|DATA@COUNT:2
** Para copias de seguridad de registros solo a pedido: Ondemand|LOG@COUNT:2


* *SC_RESOURCE_GROUP_NAME* especifica el nombre del grupo de recursos.
+
Ejemplo: RG1

* *SC_BACKUP_POLICY_NAME* especifica el nombre de la política de copia de seguridad.
+
Ejemplo: backup_policy

* *SC_AV_NAME* especifica los nombres de los volúmenes de la aplicación.
+
Ejemplo: AV1|AV2

* *SC_PRIMARY_DATA_VOLUME_FULL_PATH* especifica la asignación de almacenamiento de SVM al volumen para el directorio de archivos de datos.  Será el nombre del volumen padre para luns y qtrees.
+
Los datos se formatearán como <db1>@<SVM1:volume1>|<db2>@<SVM2:volume2>.

+
Ejemplos:

+
** Para 2 bases de datos en el mismo grupo de recursos: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA|NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA
** Para una única base de datos con archivos de datos distribuidos en varios volúmenes: buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA,herculus:/vol/scspr2417819002_NFS


* *SC_PRIMARY_ARCHIVELOGS_VOLUME_FULL_PATH* especifica la asignación de almacenamiento de SVM al volumen para el directorio de archivos de registros.  Será el nombre del volumen padre para luns y qtrees.
+
Ejemplos:

+
** Para una sola instancia de base de datos: buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO
** Para múltiples instancias de base de datos: NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO|NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO


* *SC_PRIMARY_FULL_SNAPSHOT_NAME_FOR_TAG* especifica la lista de instantáneas que contienen el nombre del sistema de almacenamiento y el nombre del volumen.
+
Ejemplos:

+
** Para una sola instancia de base de datos: buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** Para varias instancias de base de datos: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1 |NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA/RG2_scspr2417819002_21-07-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO/RG2_scspr2417819002_21-07-2021_02.28.26.3973_1


* *SC_PRIMARY_SNAPSHOT_NAMES* especifica los nombres de las instantáneas principales creadas durante la copia de seguridad.
+
Ejemplos:

+
** Para una sola instancia de base de datos: RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** Para varias instancias de base de datos: NFSB32@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1|NFSB31@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** Para mantener la coherencia, el grupo de instantáneas que involucra 2 volúmenes: cg3_R80404CBEF5V1_04-05-2021_03.08.03.4945_0_bfc279cc-28ad-465c-9d60-5487ac17b25d_2021_4_5_3_8_58_350


* *SC_PRIMARY_MOUNT_POINTS* especifica los detalles del punto de montaje que forman parte de la copia de seguridad.
+
Los detalles incluyen el directorio en el que se montan los volúmenes y no el padre inmediato del archivo respaldado.  Para una configuración ASM, es el nombre del grupo de discos.

+
Los datos se formatearán como <db1>@<mountpoint1,mountpoint2>|<db2>@<mountpoint1,mountpoint2>.

+
Ejemplos:

+
** Para una sola instancia de base de datos: /mnt/nfsdb3_data,/mnt/nfsdb3_log,/mnt/nfsdb3_data1
** Para múltiples instancias de base de datos: NFSB31@/mnt/nfsdb31_data,/mnt/nfsdb31_log,/mnt/nfsdb31_data1|NFSB32@/mnt/nfsdb32_data,/mnt/nfsdb32_log,/mnt/nfsdb32_data1
** Para ASM: +DATA2DG,+LOG2DG


* *SC_PRIMARY_SNAPSHOTS_AND_MOUNT_POINTS* especifica los nombres de las instantáneas creadas durante la copia de seguridad de cada uno de los puntos de montaje.
+
Ejemplos:

+
** Para una sola instancia de base de datos: RG2_scspr2417819002_07-21-2021_02.28.26.3973_0:/mnt/nfsb32_data,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1:/mnt/nfsb31_log
** Para múltiples instancias de base de datos: NFSB32@RG2_scspr2417819002_21-07-2021_02.28.26.3973_0:/mnt/nfsb32_data,RG2_scspr2417819002_21-07-2021_02.28.26.3973_1:/mnt/nfsb31_log|NFSB31@RG2_scspr2417819002_21-07-2021_02.28.26.3973_0:/mnt/nfsb31_data,RG2_scspr2417819002_21-07-2021_02.28.26.3973_1:/mnt/nfsb32_log


* *SC_ARCHIVELOGS_LOCATIONS* especifica la ubicación del directorio de registros de archivo.
+
Los nombres de directorio serán el padre inmediato de los archivos de registro de archivo.  Si los registros de archivo se colocan en más de una ubicación, se capturarán todas las ubicaciones.  Esto también incluye los escenarios FRA.  Si se utilizan enlaces suaves para el directorio, se completarán los mismos.

+
Ejemplos:

+
** Para una sola base de datos en NFS: /mnt/nfsdb2_log
** Para múltiples bases de datos en NFS y para los registros de archivo de base de datos NFSB31 que se ubican en dos ubicaciones diferentes: NFSB31@/mnt/nfsdb31_log1,/mnt/nfsdb31_log2|NFSB32@/mnt/nfsdb32_log
** Para ASM: +LOG2DG/ASMDB2/ARCHIVELOG/2021_07_15


* *SC_REDO_LOGS_LOCATIONS* especifica la ubicación del directorio de registros de rehacer.
+
Los nombres de directorio serán el padre inmediato de los archivos de registro de rehacer.  Si se utilizan enlaces suaves para el directorio, se completarán los mismos.

+
Ejemplos:

+
** Para una única base de datos en NFS: /mnt/nfsdb2_data/newdb1
** Para múltiples bases de datos en NFS: NFSB31@/mnt/nfsdb31_data/newdb31|NFSB32@/mnt/nfsdb32_data/newdb32
** Para ASM: +LOG2DG/ASMDB2/ONLINELOG


* *SC_CONTROL_FILES_LOCATIONS* especifica la ubicación del directorio de archivos de control.
+
Los nombres de directorio serán el padre inmediato de los archivos de control.  Si se utilizan enlaces suaves para el directorio, se completarán los mismos.

+
Ejemplos:

+
** Para una sola base de datos en NFS: /mnt/nfsdb2_data/fra/newdb1,/mnt/nfsdb2_data/newdb1
** Para múltiples bases de datos en NFS: NFSB31@/mnt/nfsdb31_data/fra/newdb31,/mnt/nfsdb31_data/newdb31|NFSB32@/mnt/nfsdb32_data/fra/newdb32,/mnt/nfsdb32_data/newdb32
** Para ASM: +LOG2DG/ASMDB2/CONTROLFILE


* *SC_DATA_FILES_LOCATIONS*" especifica la ubicación del directorio de archivos de datos.
+
Los nombres de directorio serán el padre inmediato de los archivos de datos.  Si se utilizan enlaces suaves para el directorio, se completarán los mismos.

+
Ejemplos:

+
** Para una sola base de datos en NFS: /mnt/nfsdb3_data1,/mnt/nfsdb3_data/NEWDB3/datafile
** Para múltiples bases de datos en NFS: NFSB31@/mnt/nfsdb31_data1,/mnt/nfsdb31_data/NEWDB31/datafile|NFSB32@/mnt/nfsdb32_data1,/mnt/nfsdb32_data/NEWDB32/datafile
** Para ASM: +DATA2DG/ASMDB2/ARCHIVO DE DATOS,+DATA2DG/ASMDB2/ARCHIVO TEMPORAL


* *SC_SNAPSHOT_LABEL* especifica el nombre de las etiquetas secundarias.
+
Ejemplos: Por hora, por día, por semana, por mes o etiqueta personalizada.





== Delimitadores admitidos

* *:* se utiliza para separar el nombre de SVM y el nombre del volumen
+
Ejemplo: buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_21-07-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_21-07-2021_02.28.26.3973_1

* *@* se utiliza para separar los datos de su nombre de base de datos y para separar el valor de su clave.
+
Ejemplos:

+
** NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_21-07-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_21-07-2021_02.28.26.3973_1 |NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA/RG2_scspr2417819002_21-07-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO/RG2_scspr2417819002_21-07-2021_02.28.26.3973_1
** NFSB31@oracle|NFSB32@oracle


* *|* se utiliza para separar los datos entre dos bases de datos diferentes y para separar los datos entre dos entidades diferentes para los parámetros SC_BACKUP_ID, SC_BACKUP_RETENTION y SC_BACKUP_NAME.
+
Ejemplos:

+
** DATOS@203|REGISTRO@205
** Cada hora|DATOS@DÍAS:3|REGISTRO@CONTADOR:4
** DATOS@RG2_scspr2417819002_20-07-2021_12.16.48.9267_0|REGISTRO@RG2_scspr2417819002_20-07-2021_12.16.48.9267_1


* */* se utiliza para separar el nombre del volumen de su instantánea para los parámetros SC_PRIMARY_SNAPSHOT_NAMES y SC_PRIMARY_FULL_SNAPSHOT_NAME_FOR_TAG.
+
Ejemplo: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_21-07-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_21-07-2021_02.28.26.3973_1

* *,* se utiliza para separar conjuntos de variables para la misma base de datos.
+
Ejemplo: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_21-07-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_21-07-2021_02.28.26.3973_1 |NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA/RG2_scspr2417819002_21-07-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO/RG2_scspr2417819002_21-07-2021_02.28.26.3973_1


