---
permalink: protect-sce/reference_granular_recovery_of_mails_and_mailbox.html 
sidebar: sidebar 
keywords: SMBR, Single Mailbox recovery, Exchange database 
summary: 'El software Single Mailbox Recovery (SMBR) le permite restaurar y recuperar correos o buzones en lugar de la base de datos de Exchange completa.' 
---
= Recuperación granular de correos y buzones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El software Single Mailbox Recovery (SMBR) le permite restaurar y recuperar correos o buzones en lugar de la base de datos de Exchange completa.

Restaurar una base de datos completa sólo para recuperar un solo correo consumirá mucho tiempo y recursos.  SMBR ayuda a recuperar rápidamente los correos creando una copia clonada de la instantánea y luego utilizando las API de Microsoft para montar el buzón en SMBR.  Para obtener información sobre cómo utilizar SMBR, consulte https://docs.netapp.com/p/snap/smbr/8.3/Administrative-Server-Administration-Guide.pdf["Guía de administración de SMBR"^] .

Para obtener información adicional sobre SMBR, consulte lo siguiente:

* https://kb.netapp.com/Legacy/SMBR/How_to_manually_restore_a_single_item_with_SMBR["Cómo restaurar manualmente un solo elemento con SMBR (también aplicable para restauraciones de Ontrack Power Control)"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Single_Mailbox_Recovery_(SMBR)/How_to_restore_from_secondary_storage_in_SMBR_with_SnapCenter["Cómo restaurar desde el almacenamiento secundario en SMBR con SnapCenter"^]
* https://www.youtube.com/watch?v=wMSo049rREY&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg&index=3["Recuperación de correo de Microsoft Exchange desde SnapVault mediante SMBR"^]

