---
permalink: protect-sce/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_exchange_database.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Debe crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar los cmdlets de PowerShell para realizar copias de seguridad y restaurar.' 
---
= Cree una conexión al sistema de almacenamiento y una credencial mediante cmdlets de PowerShell para Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar los cmdlets de PowerShell para realizar copias de seguridad y restaurar.

.Antes de empezar
* Debería haber preparado el entorno de PowerShell para ejecutar los cmdlets de PowerShell.
* Debe tener los permisos necesarios en el rol de administrador de infraestructura para crear conexiones de almacenamiento.
* Debe asegurarse de que las instalaciones del complemento no estén en curso.
+
Las instalaciones de complementos de host no deben estar en progreso mientras se agrega una conexión al sistema de almacenamiento porque es posible que la memoria caché del host no se actualice y el estado de las bases de datos puede mostrarse en la GUI de SnapCenter como "`No disponible para respaldo`" o "`No en almacenamiento de NetApp ".

* Los nombres de los sistemas de almacenamiento deben ser únicos.
+
SnapCenter no admite varios sistemas de almacenamiento con el mismo nombre en diferentes clústeres.  Cada sistema de almacenamiento compatible con SnapCenter debe tener un nombre único y una dirección IP LIF de datos única.



.Pasos
. Inicie una sesión de conexión de PowerShell mediante el `Open-SmConnection` cmdlet.
+
Este ejemplo abre una sesión de PowerShell:

+
[listing]
----
PS C:\> Open-SmConnection
----
. Cree una nueva conexión al sistema de almacenamiento mediante el uso del `Add-SmStorageConnection` cmdlet.
+
Este ejemplo crea una nueva conexión al sistema de almacenamiento:

+
[listing]
----
PS C:\> Add-SmStorageConnection -SVM test_vs1 -Protocol Https
-Timeout 60
----
. Cree una nueva cuenta Ejecutar como mediante el uso de `Add-Credential` cmdlet.
+
Este ejemplo crea una nueva cuenta Ejecutar como denominada ExchangeAdmin con credenciales de Windows:

+
[listing]
----
PS C:> Add-SmCredential -Name ExchangeAdmin -AuthMode Windows
-Credential sddev\administrator
----


La información sobre los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help command_name_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets del software SnapCenter"^] .
