---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenter utiliza credenciales para autenticar a los usuarios para las operaciones de SnapCenter .  Debe crear credenciales para instalar el paquete de complemento y credenciales adicionales para realizar operaciones de protección de datos en las bases de datos. 
---
= Configurar credenciales para el complemento SnapCenter para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utiliza credenciales para autenticar a los usuarios para las operaciones de SnapCenter .  Debe crear credenciales para instalar el paquete de complemento y credenciales adicionales para realizar operaciones de protección de datos en las bases de datos.

.Acerca de esta tarea
Debe configurar credenciales para instalar complementos en hosts de Windows.  Si bien puede crear credenciales para Windows después de implementar hosts e instalar complementos, la mejor práctica es crear credenciales después de agregar SVM, antes de implementar hosts e instalar complementos.

Configure las credenciales con privilegios de administrador, incluidos derechos de administrador en el host remoto.

Si configura credenciales para grupos de recursos individuales y el nombre de usuario no tiene privilegios de administrador completos, debe asignar al menos los privilegios de grupo de recursos y de respaldo al nombre de usuario.

.Pasos
. En el panel de navegación izquierdo, haga clic en *Configuración*.
. En la página de Configuración, haga clic en *Credencial*.
. Haga clic en *Nuevo*.
+
Se muestra la ventana Credencial.

. En la página Credencial, haga lo siguiente:
+
|===
| Para este campo... | Haz esto... 


 a| 
Nombre de la credencial
 a| 
Introduzca un nombre para la credencial.



 a| 
Nombre de usuario
 a| 
Introduzca el nombre de usuario utilizado para la autenticación.

** Administrador del dominio o cualquier miembro del grupo de administradores
+
Especifique el administrador del dominio o cualquier miembro del grupo de administradores del sistema donde va a instalar el complemento de SnapCenter . Los formatos válidos para el campo Nombre de usuario son:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrador local (sólo para grupos de trabajo)
+
Para los sistemas que pertenecen a un grupo de trabajo, especifique el administrador local integrado en el sistema donde va a instalar el complemento de SnapCenter . Puede especificar una cuenta de usuario local que pertenezca al grupo de administradores locales si esta cuenta tiene privilegios elevados o si la función de control de acceso de usuario está deshabilitada en el sistema host.  El formato válido para el campo Nombre de usuario es: `UserName`





 a| 
Password
 a| 
Introduzca la contraseña utilizada para la autenticación.



 a| 
Autenticación
 a| 
Seleccione Windows como modo de autenticación.

|===
. Haga clic en *Aceptar*.

