---
permalink: protect-sce/task_import_CA_certificates.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Importar los certificados de CA del servidor SnapCenter y los complementos del host de Windows 
---
= Importar certificados de CA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe importar los certificados de CA al servidor SnapCenter y a los complementos del host de Windows mediante la consola de administración de Microsoft (MMC).

.Pasos
. Vaya a la consola de administración de Microsoft (MMC) y haga clic en *Archivo* > *Agregar o quitar complemento*.
. En la ventana Agregar o quitar complementos, seleccione *Certificados* y luego haga clic en *Agregar*.
. En la ventana del complemento Certificados, seleccione la opción *Cuenta de equipo* y haga clic en *Finalizar*.
. Haga clic en *Consola raíz* > *Certificados – Equipo local* > *Autoridades de certificación raíz de confianza* > *Certificados*.
. Haga clic con el botón derecho en la carpeta “Autoridades de certificación raíz de confianza” y luego seleccione *Todas las tareas* > *Importar* para iniciar el asistente de importación.
. Complete el asistente de la siguiente manera:
+
|===
| En esta ventana del asistente... | Haz lo siguiente... 


 a| 
Importar clave privada
 a| 
Seleccione la opción *Sí*, importe la clave privada y luego haga clic en *Siguiente*.



 a| 
Formato de archivo de importación
 a| 
No realice cambios; haga clic en *Siguiente*.



 a| 
Seguridad
 a| 
Especifique la nueva contraseña que se utilizará para el certificado exportado y luego haga clic en *Siguiente*.



 a| 
Cómo completar el Asistente para importar certificados
 a| 
Revise el resumen y luego haga clic en *Finalizar* para iniciar la importación.

|===
+

NOTE: El certificado de importación debe incluirse junto con la clave privada (los formatos admitidos son: *.pfx, *.p12 y *.p7b).

. Repita el paso 5 para la carpeta “Personal”.

