---
permalink: protect-sce/task_define_a_backup_strategy_for_exchange_server_resources.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: 'Definir una estrategia de respaldo antes de crear sus trabajos de respaldo le ayudará a garantizar que tenga los respaldos que necesita para restaurar exitosamente sus bases de datos.  Su acuerdo de nivel de servicio (SLA), su objetivo de tiempo de recuperación (RTO) y su objetivo de punto de recuperación (RPO) determinan en gran medida su estrategia de respaldo.' 
---
= Definir una estrategia de respaldo para los recursos de Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Definir una estrategia de respaldo antes de crear sus trabajos de respaldo le ayudará a garantizar que tenga los respaldos que necesita para restaurar exitosamente sus bases de datos.  Su acuerdo de nivel de servicio (SLA), su objetivo de tiempo de recuperación (RTO) y su objetivo de punto de recuperación (RPO) determinan en gran medida su estrategia de respaldo.

Un SLA define el nivel de servicio esperado y aborda muchas cuestiones relacionadas con el servicio, incluida la disponibilidad y el rendimiento del servicio.  El RTO es el tiempo en el que se debe restaurar un proceso comercial después de una interrupción en el servicio.  Un RPO define la estrategia para la antigüedad de los archivos que deben recuperarse del almacenamiento de respaldo para que las operaciones normales se reanuden después de una falla.  El SLA, RTO y RPO contribuyen a la estrategia de respaldo.



== Tipos de copias de seguridad compatibles con la base de datos de Exchange

Para realizar copias de seguridad de buzones de Exchange mediante SnapCenter es necesario elegir el tipo de recurso, como bases de datos y grupos de disponibilidad de bases de datos (DAG).  Se aprovecha la tecnología de instantáneas para crear copias en línea, de solo lectura, de los volúmenes en los que residen los recursos.

|===
| Tipo de copia de seguridad | Descripción 


 a| 
Copia de seguridad completa y de registros
 a| 
Realiza una copia de seguridad de las bases de datos y de todos los registros de transacciones, incluidos los registros truncados.

Una vez completada una copia de seguridad completa, Exchange Server trunca los registros de transacciones que ya están confirmados en la base de datos.

Por lo general, deberías elegir esta opción.  Sin embargo, si el tiempo de respaldo es corto, puede elegir no ejecutar una copia de seguridad del registro de transacciones con una copia de seguridad completa.



 a| 
Copia de seguridad completa
 a| 
Realiza copias de seguridad de bases de datos y registros de transacciones.

No se realiza una copia de seguridad de los registros de transacciones truncados.



 a| 
Copia de seguridad del registro
 a| 
Realiza una copia de seguridad de todos los registros de transacciones.

Los registros truncados que ya están confirmados en la base de datos no se respaldan.  Si programa copias de seguridad frecuentes del registro de transacciones entre copias de seguridad completas de la base de datos, puede elegir puntos de recuperación granulares.

|===


== Programaciones de copias de seguridad para complementos de bases de datos

La frecuencia de copia de seguridad (tipo de programación) se especifica en las políticas; una programación de copia de seguridad se especifica en la configuración del grupo de recursos.  El factor más crítico a la hora de determinar la frecuencia o el cronograma de una copia de seguridad es la tasa de cambio del recurso y la importancia de los datos.  Es posible que hagas una copia de seguridad de un recurso muy utilizado cada hora, mientras que es posible que hagas una copia de seguridad de un recurso poco utilizado una vez al día.  Otros factores incluyen la importancia del recurso para su organización, su Acuerdo de Nivel de Servicio (SLA) y su Objetivo de Punto de Recuperación (RPO).

Un SLA define el nivel de servicio esperado y aborda muchas cuestiones relacionadas con el servicio, incluida la disponibilidad y el rendimiento del servicio.  Un RPO define la estrategia para la antigüedad de los archivos que deben recuperarse del almacenamiento de respaldo para que las operaciones normales se reanuden después de una falla.  El SLA y el RPO contribuyen a la estrategia de protección de datos.

Incluso para un recurso muy utilizado, no es necesario ejecutar una copia de seguridad completa más de una o dos veces al día.  Por ejemplo, las copias de seguridad periódicas del registro de transacciones podrían ser suficientes para garantizar que tenga las copias de seguridad que necesita.  Cuanto más a menudo realice copias de seguridad de sus bases de datos, menos registros de transacciones tendrá que utilizar SnapCenter en el momento de la restauración, lo que puede generar operaciones de restauración más rápidas.

Los programas de respaldo constan de dos partes, como se indica a continuación:

* Frecuencia de respaldo
+
La frecuencia de las copias de seguridad (con qué frecuencia se deben realizar las copias de seguridad), denominada _tipo de programación_ para algunos complementos, es parte de una configuración de políticas.  Puede seleccionar la frecuencia de respaldo para la política: horaria, diaria, semanal o mensual.  Si no selecciona ninguna de estas frecuencias, la política creada será solo a pedido.  Puede acceder a las políticas haciendo clic en *Configuración* > *Políticas*.

* Programaciones de copias de seguridad
+
Las programaciones de copias de seguridad (exactamente cuándo se deben realizar las copias de seguridad) son parte de la configuración de un grupo de recursos.  Por ejemplo, si tiene un grupo de recursos que tiene una política configurada para realizar copias de seguridad semanales, puede configurar la programación para realizar copias de seguridad todos los jueves a las 10:00 p. m.  Puede acceder a los programas de grupos de recursos haciendo clic en *Recursos* > *Grupos de recursos*.





== Número de trabajos de respaldo necesarios para las bases de datos

Los factores que determinan la cantidad de trabajos de respaldo que necesita incluyen el tamaño del recurso, la cantidad de volúmenes utilizados, la tasa de cambio del recurso y su Acuerdo de Nivel de Servicio (SLA).



== Convenciones de nombres de copias de seguridad

Puede utilizar la convención de nombres de instantáneas predeterminada o utilizar una convención de nombres personalizada.  La convención de nombres de copia de seguridad predeterminada agrega una marca de tiempo a los nombres de las instantáneas que le ayuda a identificar cuándo se crearon las copias.

La instantánea utiliza la siguiente convención de nombres predeterminada:

`resourcegroupname_hostname_timestamp`

Debes nombrar tus grupos de recursos de respaldo de forma lógica, como en el siguiente ejemplo:

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
En este ejemplo, los elementos de sintaxis tienen los siguientes significados:

* _dts1_ es el nombre del grupo de recursos.
* _mach1x88_ es el nombre del host.
* _03-12-2015_23.17.26_ es la fecha y la marca de tiempo.


Como alternativa, puede especificar el formato del nombre de la instantánea mientras protege recursos o grupos de recursos seleccionando *Usar formato de nombre personalizado para copia de instantánea*.  Por ejemplo, customtext_resourcegroup_policy_hostname o resourcegroup_hostname.  De forma predeterminada, el sufijo de marca de tiempo se agrega al nombre de la instantánea.



== Opciones de retención de copias de seguridad

Puede elegir la cantidad de días durante los cuales desea conservar copias de seguridad o especificar la cantidad de copias de seguridad que desea conservar, hasta un máximo de 255 copias en ONTAP .  Por ejemplo, su organización podría exigirle que conserve 10 días de copias de seguridad o 130 copias de seguridad.

Al crear una política, puede especificar las opciones de retención para el tipo de copia de seguridad y el tipo de programación.

Si configura la replicación de SnapMirror , la política de retención se refleja en el volumen de destino.

SnapCenter elimina las copias de seguridad retenidas que tienen etiquetas de retención que coinciden con el tipo de programación.  Si se modificó el tipo de programación del recurso o del grupo de recursos, es posible que las copias de seguridad con la etiqueta del tipo de programación anterior aún permanezcan en el sistema.


NOTE: Para la retención a largo plazo de copias de seguridad, debe utilizar la copia de seguridad SnapVault .



== ¿Durante cuánto tiempo se deben conservar las copias de seguridad del registro de transacciones en el volumen de almacenamiento de origen para Exchange Server?

El complemento SnapCenter para Microsoft Exchange Server necesita copias de seguridad del registro de transacciones para realizar operaciones de restauración actualizadas, que restauran su base de datos a un tiempo entre dos copias de seguridad completas.

Por ejemplo, si Plug-in for Exchange realizó una copia de seguridad completa del registro de transacciones a las 8:00 a. m. y otra copia de seguridad completa del registro de transacciones a las 5:00 p. m., podría usar la última copia de seguridad del registro de transacciones para restaurar la base de datos a cualquier momento entre las 8:00 a. m. y las 5:00 p. m. Si los registros de transacciones no están disponibles, Plug-in for Exchange solo puede realizar operaciones de restauración en un punto en el tiempo, que restauran una base de datos al momento en que Plug-in for Exchange completó una copia de seguridad completa.

Por lo general, se necesitan operaciones de restauración actualizadas solo por uno o dos días.  De forma predeterminada, SnapCenter conserva un mínimo de dos días.
