---
permalink: protect-scw/reference_installation_requirements_for_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: requirements 
summary: Debe tener en cuenta ciertos requisitos de instalación antes de instalar el complemento para Windows. 
---
= Requisitos de instalación del complemento SnapCenter para Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener en cuenta ciertos requisitos de instalación antes de instalar el complemento para Windows.

Antes de comenzar a utilizar el complemento para Windows, el administrador de SnapCenter debe instalar y configurar SnapCenter Server y realizar las tareas previas requeridas.

* Debe tener privilegios de administrador de SnapCenter para instalar el complemento para Windows.
+
El rol de administrador de SnapCenter debe tener privilegios de administrador.

* Debe tener instalado y configurado el servidor SnapCenter .
* Al instalar un complemento en un host de Windows, si especifica una credencial que no está incorporada o si el usuario pertenece a un usuario de grupo de trabajo local, debe deshabilitar UAC en el host.
* Debe configurar SnapMirror y SnapVault si desea replicar la copia de seguridad.




== Requisitos del host para instalar el paquete de complementos de SnapCenter para Windows

Antes de instalar el paquete de complementos de SnapCenter para Windows, debe familiarizarse con algunos requisitos básicos de espacio y tamaño del sistema host.

|===
| Artículo | Requisitos 


 a| 
Sistemas operativos
 a| 
Microsoft Windows

Para obtener la información más reciente sobre las versiones compatibles, consulte la https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] .

Si está en una configuración de clúster de Windows, también debe instalar y configurar la Administración remota de Windows (WinRM).



 a| 
RAM mínima para el complemento SnapCenter en el host
 a| 
1 GB



 a| 
Espacio mínimo de instalación y registro para el complemento SnapCenter en el host
 a| 
5 GB


NOTE: Debe asignar suficiente espacio en disco y supervisar el consumo de almacenamiento de la carpeta de registros.  El espacio de registro necesario varía según la cantidad de entidades a proteger y la frecuencia de las operaciones de protección de datos.  Si no hay suficiente espacio en disco, no se crearán registros para las operaciones ejecutadas recientemente.



 a| 
Paquetes de software necesarios
 a| 
* Paquete de alojamiento de ASP.NET Core Runtime 8.0.12 (y todos los parches 8.0.x posteriores)
* PowerShell Core 7.4.2


Para obtener la información más reciente sobre las versiones compatibles, consulte la https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] .

Para obtener información de solución de problemas específicos de .NET, consulte https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["La actualización o instalación de SnapCenter falla en los sistemas heredados que no tienen conectividad a Internet."]

|===


== Configure sus credenciales para el complemento para Windows

SnapCenter utiliza credenciales para autenticar a los usuarios para las operaciones de SnapCenter .  Debe crear credenciales para instalar complementos de SnapCenter y credenciales adicionales para realizar operaciones de protección de datos en los sistemas de archivos de Windows.

*Lo que necesitarás*

* Debe configurar las credenciales de Windows antes de instalar complementos.
* Debe configurar las credenciales con privilegios de administrador, incluidos derechos de administrador, en el host remoto.
* Si configura credenciales para grupos de recursos individuales y el usuario no tiene privilegios de administrador completos, debe asignarle al menos los privilegios de grupo de recursos y de respaldo.


*Pasos*

. En el panel de navegación izquierdo, haga clic en *Configuración*.
. En la página de Configuración, haga clic en *Credencial*.
. Haga clic en *Nuevo*.
. En la página Credencial, haga lo siguiente:
+
|===
| Para este campo... | Haz esto... 


 a| 
Nombre de la credencial
 a| 
Introduzca un nombre para las credenciales.



 a| 
Nombre de usuario/Contraseña
 a| 
Introduzca el nombre de usuario y la contraseña utilizados para la autenticación.

** Administrador del dominio o cualquier miembro del grupo de administradores
+
Especifique el administrador del dominio o cualquier miembro del grupo de administradores del sistema donde va a instalar el complemento de SnapCenter . Los formatos válidos para el campo Nombre de usuario son los siguientes:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`
*** `UserName@upn`


** Administrador local (sólo para grupos de trabajo)
+
Para los sistemas que pertenecen a un grupo de trabajo, especifique el administrador local integrado en el sistema donde va a instalar el complemento de SnapCenter . Puede especificar una cuenta de usuario local que pertenezca al grupo de administradores locales si esta cuenta tiene privilegios elevados o si la función de control de acceso de usuario está deshabilitada en el sistema host.  El formato válido para el campo Nombre de usuario es el siguiente: `UserName`

+
No utilice comillas dobles (") ni tildes invertidas (`) en las contraseñas.  No debe utilizar los símbolos menor que (<) y exclamación (!) juntos en las contraseñas.  Por ejemplo, menos que<!10, menos que10<!, acento grave`12.





 a| 
Password
 a| 
Introduzca la contraseña utilizada para la autenticación.

|===
. Haga clic en *Aceptar*.
+
Después de terminar de configurar las credenciales, es posible que desee asignar el mantenimiento de credenciales a un usuario o grupo de usuarios en la página Usuario y acceso.





== Configurar gMSA en Windows Server 2016 o posterior

Windows Server 2016 o posterior le permite crear una cuenta de servicio administrada de grupo (gMSA) que proporciona administración automatizada de contraseñas de cuentas de servicio desde una cuenta de dominio administrada.

.Antes de empezar
* Debe tener un controlador de dominio de Windows Server 2016 o posterior.
* Debe tener un host de Windows Server 2016 o posterior, que sea miembro del dominio.


.Pasos
. Cree una clave raíz KDS para generar contraseñas únicas para cada objeto en su gMSA.
. Para cada dominio, ejecute el siguiente comando desde el controlador de dominio de Windows: Add-KDSRootKey -EffectiveImmediately
. Cree y configure su gMSA:
+
.. Cree una cuenta de grupo de usuarios con el siguiente formato:
+
 domainName\accountName$
.. Añade objetos de computadora al grupo.
.. Utilice el grupo de usuarios que acaba de crear para crear el gMSA.
+
Por ejemplo,

+
 New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>
.. Correr `Get-ADServiceAccount` Comando para verificar la cuenta de servicio.


. Configure el gMSA en sus hosts:
+
.. Habilite el módulo Active Directory para Windows PowerShell en el host donde desea utilizar la cuenta gMSA.
+
Para hacer esto, ejecute el siguiente comando desde PowerShell:

+
[listing]
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
.. Reinicie su host.
.. Instale gMSA en su host ejecutando el siguiente comando desde el símbolo del sistema de PowerShell: `Install-AdServiceAccount <gMSA>`
.. Verifique su cuenta gMSA ejecutando el siguiente comando: `Test-AdServiceAccount <gMSA>`


. Asigne los privilegios administrativos al gMSA configurado en el host.
. Agregue el host de Windows especificando la cuenta gMSA configurada en el servidor SnapCenter .
+
SnapCenter Server instalará los complementos seleccionados en el host y la gMSA especificada se utilizará como cuenta de inicio de sesión de servicio durante la instalación del complemento.


