---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup strategy 
summary: 'Definir una estrategia de respaldo antes de crear sus copias de seguridad le proporcionará las copias de seguridad que necesita para restaurar o clonar con éxito sus sistemas de archivos.  Su acuerdo de nivel de servicio (SLA), su objetivo de tiempo de recuperación (RTO) y su objetivo de punto de recuperación (RPO) determinan en gran medida su estrategia de respaldo.' 
---
= Definir una estrategia de respaldo para los sistemas de archivos de Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Definir una estrategia de respaldo antes de crear sus copias de seguridad le proporcionará las copias de seguridad que necesita para restaurar o clonar con éxito sus sistemas de archivos.  Su acuerdo de nivel de servicio (SLA), su objetivo de tiempo de recuperación (RTO) y su objetivo de punto de recuperación (RPO) determinan en gran medida su estrategia de respaldo.

Un SLA define el nivel de servicio que se espera y aborda muchas cuestiones relacionadas con el servicio, incluida la disponibilidad y el rendimiento del servicio.  RTO es el tiempo en el que se debe restaurar un proceso comercial después de una interrupción en el servicio.  RPO define la estrategia para la edad de los archivos que deben recuperarse del almacenamiento de respaldo para que las operaciones normales se reanuden después de una falla.  SLA, RTO y RPO contribuyen a la estrategia de protección de datos.



== Programaciones de copias de seguridad para sistemas de archivos de Windows

La frecuencia de las copias de seguridad se especifica en las políticas; una programación de copias de seguridad se especifica en la configuración del grupo de recursos.  El factor más crítico a la hora de determinar la frecuencia o el cronograma de una copia de seguridad es la tasa de cambio del recurso y la importancia de los datos.  Es posible que hagas una copia de seguridad de un recurso muy utilizado cada hora, mientras que es posible que hagas una copia de seguridad de un recurso poco utilizado una vez al día.  Otros factores incluyen la importancia del recurso para su organización, su Acuerdo de Nivel de Servicio (SLA) y su Objetivo de Punto de Recuperación (RPO).

Un SLA define el nivel de servicio esperado y aborda muchas cuestiones relacionadas con el servicio, incluida la disponibilidad y el rendimiento del servicio.  Un RPO define la estrategia para la antigüedad de los archivos que deben recuperarse del almacenamiento de respaldo para que las operaciones normales se reanuden después de una falla.  El SLA y el RPO contribuyen a la estrategia de protección de datos.

Incluso para un recurso muy utilizado, no es necesario ejecutar una copia de seguridad completa más de una o dos veces al día.

Los programas de respaldo constan de dos partes, como se indica a continuación:

* Frecuencia de respaldo
+
La frecuencia de las copias de seguridad (con qué frecuencia se deben realizar las copias de seguridad), denominada _tipo de programación_ para algunos complementos, es parte de una configuración de políticas.  Por ejemplo, puede configurar la frecuencia de la copia de seguridad como horaria, diaria, semanal o mensual, o puede especificar *Ninguno*, lo que hace que la política sea solo a pedido.  Puede acceder a las políticas haciendo clic en *Configuración* > *Políticas*.

* Programaciones de copias de seguridad
+
Las programaciones de copias de seguridad (exactamente cuándo se deben realizar las copias de seguridad) son parte de la configuración de un grupo de recursos.  Por ejemplo, si tiene un grupo de recursos que tiene una política configurada para realizar copias de seguridad semanales, puede configurar la programación para realizar copias de seguridad todos los jueves a las 10:00 p. m.  Puede acceder a los programas de grupos de recursos haciendo clic en *Recursos* > *Grupos de recursos*.





== Número de copias de seguridad necesarias para los sistemas de archivos de Windows

Los factores que determinan la cantidad de copias de seguridad que necesita incluyen el tamaño del sistema de archivos de Windows, la cantidad de volúmenes utilizados, la tasa de cambio del sistema de archivos y su Acuerdo de Nivel de Servicio (SLA).



== Convención de nomenclatura de copias de seguridad para sistemas de archivos de Windows

Las copias de seguridad del sistema de archivos de Windows utilizan la convención de nombres de instantáneas predeterminada.  La convención de nombres de copia de seguridad predeterminada agrega una marca de tiempo a los nombres de las instantáneas que le ayuda a identificar cuándo se crearon las copias.

La instantánea utiliza la siguiente convención de nombres predeterminada: resourcegroupname_hostname_timestamp

Debes nombrar tus grupos de recursos de respaldo de forma lógica, como en el siguiente ejemplo:

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
En este ejemplo, los elementos de sintaxis tienen los siguientes significados:

* `dts1`es el nombre del grupo de recursos.
* `mach1x88`es el nombre del host.
* `03-12-2016_23.17.26`Es la fecha y la marca de tiempo.


Al crear una copia de seguridad, también puede agregar una etiqueta descriptiva para ayudar a identificar la copia de seguridad.  Por el contrario, si desea utilizar una convención de nombres de copia de seguridad personalizada, deberá cambiar el nombre de la copia de seguridad una vez completada la operación.



== Opciones de retención de copias de seguridad

Puede elegir la cantidad de días durante los cuales desea conservar copias de seguridad o especificar la cantidad de copias de seguridad que desea conservar, hasta un máximo de 255 copias en ONTAP .  Por ejemplo, su organización podría exigirle que conserve 10 días de copias de seguridad o 130 copias de seguridad.

Al crear una política, puede especificar las opciones de retención para el tipo de copia de seguridad y el tipo de programación.

Si configura la replicación de SnapMirror , la política de retención se refleja en el volumen de destino.

SnapCenter elimina las copias de seguridad retenidas que tienen etiquetas de retención que coinciden con el tipo de programación.  Si se modificó el tipo de programación del recurso o del grupo de recursos, es posible que las copias de seguridad con la etiqueta del tipo de programación anterior aún permanezcan en el sistema.


NOTE: Para la retención a largo plazo de copias de seguridad, debe utilizar la copia de seguridad SnapVault .
