---
permalink: protect-scw/task_install_on_multiple_remote_hosts_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: Si desea instalar el complemento SnapCenter para Microsoft Windows en varios hosts a la vez, puede hacerlo mediante el cmdlet de PowerShell Install-SmHostPackage. 
---
= Instalar el complemento SnapCenter para Microsoft Windows en varios hosts remotos mediante cmdlets de PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea instalar el complemento SnapCenter para Microsoft Windows en varios hosts a la vez, puede hacerlo mediante el `Install-SmHostPackage` Cmdlet de PowerShell.

Debe haber iniciado sesión en SnapCenter como usuario de dominio con derechos de administrador local en cada host en el que desee instalar complementos.

.Pasos
. Inicie PowerShell.
. En el host del servidor SnapCenter , establezca una sesión utilizando el `Open-SmConnection` cmdlet y luego ingrese sus credenciales.
. Agregue el host independiente o el clúster a SnapCenter mediante el `Add-SmHost` cmdlet y los parámetros requeridos.
+
La información sobre los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help command_name_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets del software SnapCenter"^] .

. Instale el complemento en varios hosts mediante el `Install-SmHostPackage` cmdlet y los parámetros requeridos.
+
Puedes utilizar el `-skipprecheck` Opción cuando ha instalado los complementos manualmente y no desea validar si el host cumple con los requisitos para instalar el complemento.


