---
permalink: protect-hana/concept_snapcenter_plug_in_for_sap_hana_database_features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: SnapCenter se integra con la aplicación complementaria y con las tecnologías NetApp en el sistema de almacenamiento.  Para trabajar con el complemento para la base de datos SAP HANA, utilice la interfaz gráfica de usuario de SnapCenter . 
---
= Funciones del complemento SnapCenter para la base de datos SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter se integra con la aplicación complementaria y con las tecnologías NetApp en el sistema de almacenamiento.  Para trabajar con el complemento para la base de datos SAP HANA, utilice la interfaz gráfica de usuario de SnapCenter .

* *Interfaz gráfica de usuario unificada*
+
La interfaz de SnapCenter proporciona estandarización y consistencia entre complementos y entornos.  La interfaz de SnapCenter le permite realizar operaciones consistentes de copia de seguridad, restauración y clonación en todos los complementos, utilizar informes centralizados, usar vistas de panel de un vistazo, configurar el control de acceso basado en roles (RBAC) y supervisar trabajos en todos los complementos.

* *Administración central automatizada*
+
Puede programar operaciones de respaldo, configurar la retención de respaldo basada en políticas y realizar operaciones de restauración.  También puede supervisar su entorno de forma proactiva configurando SnapCenter para enviar alertas por correo electrónico.

* *Tecnología de copia Snapshot de NetApp sin interrupciones*
+
SnapCenter utiliza la tecnología NetApp Snapshot con el complemento para la base de datos SAP HANA para realizar copias de seguridad de los recursos.



El uso del complemento para la base de datos SAP HANA también ofrece los siguientes beneficios:

* Compatibilidad con flujos de trabajo de copia de seguridad, restauración y clonación
* Seguridad respaldada por RBAC y delegación de roles centralizada
+
También puede configurar las credenciales para que los usuarios autorizados de SnapCenter tengan permisos a nivel de aplicación.

* Creación de copias puntuales y con uso eficiente del espacio de recursos para pruebas o extracción de datos mediante la tecnología NetApp FlexClone
+
Se requiere una licencia FlexClone en el sistema de almacenamiento donde desea crear el clon.

* Compatibilidad con la función de instantánea del grupo de consistencia (CG) de ONTAP como parte de la creación de copias de seguridad.
* Capacidad de ejecutar múltiples copias de seguridad simultáneamente en múltiples hosts de recursos
+
En una sola operación, las instantáneas se consolidan cuando los recursos de un solo host comparten el mismo volumen.

* Capacidad de crear instantáneas mediante comandos externos.
* Soporte para copias de seguridad basadas en archivos.
* Soporte para Linux LVM en el sistema de archivos XFS.

