---
permalink: protect-hana/concept_how_resources_resource_groups_and_policies_are_used_for_protecting_sap_hana_databases.html 
sidebar: sidebar 
keywords: SAP HANA databases 
summary: Antes de utilizar SnapCenter, es útil comprender los conceptos básicos relacionados con las operaciones de copia de seguridad, clonación y restauración que desea realizar.  Interactúa con recursos, grupos de recursos y políticas para diferentes operaciones. 
---
= Cómo se utilizan los recursos, los grupos de recursos y las políticas para proteger las bases de datos de SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de utilizar SnapCenter, es útil comprender los conceptos básicos relacionados con las operaciones de copia de seguridad, clonación y restauración que desea realizar.  Interactúa con recursos, grupos de recursos y políticas para diferentes operaciones.

* Los recursos suelen ser bases de datos de SAP HANA que usted respalda o clona con SnapCenter.
* Un grupo de recursos de SnapCenter es una colección de recursos en un host.
+
Cuando se realiza una operación en un grupo de recursos, dicha operación se realiza en los recursos definidos en el grupo de recursos según la programación que especifique para el grupo de recursos.

+
Puede realizar una copia de seguridad a pedido de un solo recurso o de un grupo de recursos.  También puede realizar copias de seguridad programadas para recursos individuales y grupos de recursos.

* Las políticas especifican la frecuencia de las copias de seguridad, la replicación, los scripts y otras características de las operaciones de protección de datos.
+
Cuando crea un grupo de recursos, selecciona una o más políticas para ese grupo.  También puede seleccionar una política cuando realiza una copia de seguridad a pedido para un solo recurso.



Piense en un grupo de recursos como si definiera lo que desea proteger y cuándo desea protegerlo en términos de día y hora.  Piense en una política como si definiera cómo desea protegerla.  Si está realizando una copia de seguridad de todas las bases de datos, por ejemplo, puede crear un grupo de recursos que incluya todas las bases de datos del host.  Luego, puede adjuntar dos políticas al grupo de recursos: una política diaria y una política por hora.  Al crear el grupo de recursos y adjuntar las políticas, puede configurar el grupo de recursos para que realice una copia de seguridad completa diariamente.
