---
permalink: protect-hana/reference_types_of_restore_strategies_supported_for_auto_discovered_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Databases 
summary: Debe definir una estrategia antes de poder realizar con éxito operaciones de restauración mediante SnapCenter.  Hay dos tipos de estrategias de restauración para las bases de datos de SAP HANA detectadas automáticamente. 
---
= Tipos de estrategias de restauración compatibles con bases de datos SAP HANA detectadas automáticamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe definir una estrategia antes de poder realizar con éxito operaciones de restauración mediante SnapCenter.  Hay dos tipos de estrategias de restauración para las bases de datos de SAP HANA detectadas automáticamente.



== Restauración completa de recursos

* Restaura todos los volúmenes, qtrees y LUN de un recurso
+
** Se debe seleccionar la opción *Volume Revert* para restaurar el volumen completo.
+

NOTE: Si el recurso contiene volúmenes o qtrees, las instantáneas tomadas después de la instantánea seleccionada para restaurar en dichos volúmenes o qtrees se eliminan y no se pueden recuperar.  Además, si algún otro recurso está alojado en los mismos volúmenes o qtrees, ese recurso también se elimina.







== Base de datos de inquilinos

* Restaura la base de datos de inquilinos


Si se selecciona la opción *Base de datos de inquilinos*, se deben usar HANA Studio o scripts de recuperación de HANA externos a SnapCenter para realizar la operación de recuperación.
