---
permalink: protect-hana/task_install_snapcenter_plug_in_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: install, VMware vSphere 
summary: 'Si su base de datos está almacenada en máquinas virtuales (VM), o si desea proteger las VM y los almacenes de datos, debe implementar el SnapCenter Plug-in for VMware vSphere .' 
---
= Instalar el SnapCenter Plug-in for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si su base de datos o sistema de archivos está almacenado en máquinas virtuales (VM), o si desea proteger las VM y los almacenes de datos, debe implementar el SnapCenter Plug-in for VMware vSphere .

Para obtener información sobre la implementación, consulte https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_get_started_overview.html["Descripción general de la implementación"^] .



== Implementar certificado de CA

Para configurar el certificado CA con el SnapCenter Plug-in for VMware vSphere, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_and_or_import_an_SSL_certificate_to_SnapCenter_Plug-in_for_VMware_vSphere_(SCV)["Crear o importar certificado SSL"^] .



== Configurar el archivo CRL

El SnapCenter Plug-in for VMware vSphere busca los archivos CRL en un directorio preconfigurado.  El directorio predeterminado de los archivos CRL para el SnapCenter Plug-in for VMware vSphere es _/opt/netapp/config/crl_.

Puede colocar más de un archivo CRL en este directorio.  Los certificados entrantes se verificarán con cada CRL.
