---
permalink: protect-hana/task_install_the_snapcenter_plug_in_for_sap_hana_database_on_linux_hosts_using_the_command_line_interface.html 
sidebar: sidebar 
keywords: install, SnapCenter Plug-in for SAP HANA Database 
summary: 'Debe instalar el complemento de SnapCenter para la base de datos SAP HANA mediante la interfaz de usuario (UI) de SnapCenter .  Si su entorno no permite la instalación remota del complemento desde la interfaz de usuario de SnapCenter , puede instalar el complemento para la base de datos SAP HANA en modo de consola o en modo silencioso mediante la interfaz de línea de comandos (CLI1).' 
---
= Instale el complemento de SnapCenter para la base de datos SAP HANA en hosts Linux mediante la interfaz de línea de comandos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe instalar el complemento de SnapCenter para la base de datos SAP HANA mediante la interfaz de usuario (UI) de SnapCenter .  Si su entorno no permite la instalación remota del complemento desde la interfaz de usuario de SnapCenter , puede instalar el complemento para la base de datos SAP HANA en modo de consola o en modo silencioso mediante la interfaz de línea de comandos (CLI).

.Antes de empezar
* Debe instalar el complemento para la base de datos SAP HANA en cada uno de los hosts Linux donde reside el cliente HDBSQL.
* El host Linux en el que está instalando el complemento de SnapCenter para la base de datos SAP HANA debe cumplir con los requisitos de software, base de datos y sistema operativo dependientes.
+
La herramienta Matriz de Interoperabilidad (IMT) contiene la información más reciente sobre las configuraciones admitidas.

+
https://imt.netapp.com/matrix/imt.jsp?components=121029;&solution=1259&isHWU&src=IMT[]

* El complemento de SnapCenter para la base de datos SAP HANA es parte del paquete de complementos de SnapCenter para Linux.  Antes de instalar el paquete de complementos de SnapCenter para Linux, ya debe haber instalado SnapCenter en un host Windows.


.Pasos
. Copie el archivo de instalación del paquete de complementos de SnapCenter para Linux (snapcenter_linux_host_plugin.bin) desde C:\ProgramData\ NetApp\ SnapCenter\Package Repository al host donde desea instalar el complemento para la base de datos SAP HANA.
+
Puede acceder a esta ruta desde el host donde está instalado SnapCenter Server.

. Desde el símbolo del sistema, navegue hasta el directorio donde copió el archivo de instalación.
. Instalar el complemento: `path_to_installation_bin_file/snapcenter_linux_host_plugin.bin -i silent -DPORT=port_number_for_host -DSERVER_IP=server_name_or_ip_address -DSERVER_HTTPS_PORT=port_number_for_server`
+
** -DPORT especifica el puerto de comunicación HTTPS de SMCore.
** -DSERVER_IP especifica la dirección IP del servidor SnapCenter .
** -DSERVER_HTTPS_PORT especifica el puerto HTTPS del servidor SnapCenter .
** -DUSER_INSTALL_DIR especifica el directorio donde desea instalar el paquete de complementos de SnapCenter para Linux.
** DINSTALL_LOG_NAME especifica el nombre del archivo de registro.


+
[listing]
----
/tmp/sc-plugin-installer/snapcenter_linux_host_plugin.bin -i silent  -DPORT=8145 -DSERVER_IP=scserver.domain.com -DSERVER_HTTPS_PORT=8146 -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=SnapCenter_Linux_Host_Plugin_Install_2.log -DCHOSEN_FEATURE_LIST=CUSTOM
----
. Edite el archivo /<directorio de instalación>/ NetApp/snapcenter/scc/etc/SC_SMS_Services.properties y luego agregue el parámetro PLUGINS_ENABLED = hana:3.0.
. Agregue el host al servidor SnapCenter mediante el cmdlet Add-Smhost y los parámetros necesarios.
+
La información sobre los parámetros que se pueden utilizar con el comando y sus descripciones se puede obtener ejecutando _Get-Help command_name_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets del software SnapCenter"^] .


