---
permalink: protect-hana/task_create_a_storage_system_connection_and_a_run_as_account_using_powershell_cmdlets_for_sap_hana_database.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: 'Debe crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar los cmdlets de PowerShell para realizar copias de seguridad, restaurar o clonar bases de datos de SAP HANA.' 
---
= Cree una conexión al sistema de almacenamiento y una credencial mediante cmdlets de PowerShell para la base de datos de SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar los cmdlets de PowerShell para realizar copias de seguridad, restaurar o clonar bases de datos de SAP HANA.

.Antes de empezar
* Debería haber preparado el entorno de PowerShell para ejecutar los cmdlets de PowerShell.
* Debe tener los permisos necesarios en el rol de administrador de infraestructura para crear conexiones de almacenamiento.
* Debe asegurarse de que las instalaciones del complemento no estén en curso.
+
Las instalaciones de complementos de host no deben estar en progreso mientras se agrega una conexión al sistema de almacenamiento porque es posible que la memoria caché del host no se actualice y el estado de las bases de datos puede mostrarse en la GUI de SnapCenter como "`No disponible para respaldo`" o "`No en almacenamiento de NetApp ".

* Los nombres de los sistemas de almacenamiento deben ser únicos.
+
SnapCenter no admite varios sistemas de almacenamiento con el mismo nombre en diferentes clústeres.  Cada sistema de almacenamiento compatible con SnapCenter debe tener un nombre único y una dirección IP LIF de datos única.



.Pasos
. Inicie una sesión de conexión de PowerShell mediante el cmdlet Open-SmConnection.
+
[listing]
----
PS C:\> Open-SmStorageConnection
----
. Cree una nueva conexión al sistema de almacenamiento mediante el cmdlet Add-SmStorageConnection.
+
[listing]
----
PS C:\> Add-SmStorageConnection -StorageType DataOntap -Type DataOntap -OntapStorage ‘scsnfssvm’ -Protocol Https -Timeout 60
----
. Cree una nueva credencial mediante el cmdlet Add-SmCredential.
+
Este ejemplo muestra cómo crear una nueva credencial llamada FinanceAdmin con credenciales de Windows:

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----
. Agregue el host de comunicación SAP HANA al servidor SnapCenter .
+
[listing]
----
PS C:> Add-SmHost -HostName 10.232.204.61 -OSType Windows -RunAsName FinanceAdmin -PluginCode hana
----
. Instale el paquete y el complemento de SnapCenter para la base de datos SAP HANA en el host.
+
Para Linux:

+
[listing]
----
PS C:> Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode hana
----
+
Para Windows:

+
[listing]
----
Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode hana -FilesystemCode scw -RunAsName FinanceAdmin
----
. Establezca la ruta al cliente HDBSQL.
+
Para Windows:

+
[listing]
----
PS C:> Set-SmConfigSettings -Plugin -HostName 10.232.204.61 -PluginCode hana -configSettings @{"HANA_HDBSQL_CMD" = "C:\Program Files\sap\hdbclient\hdbsql.exe"}
----
+
Para Linux:

+
[listing]
----
Set-SmConfigSettings -Plugin -HostName scs-hana.gdl.englab.netapp.com -PluginCode hana -configSettings @{"HANA_HDBSQL_CMD"="/usr/sap/hdbclient/hdbsql"}
----


La información sobre los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help command_name_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets del software SnapCenter"^] .
