---
sidebar: sidebar 
permalink: sc-automation/concept_basic_operational_characteristics.html 
keywords: request and response, object identifiers, synchronous, asynchronous 
summary: Si bien REST establece un conjunto común de tecnologías y mejores prácticas, los detalles de cada API pueden variar según las opciones de diseño. 
---
= Características operativas básicas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si bien REST establece un conjunto común de tecnologías y mejores prácticas, los detalles de cada API pueden variar según las opciones de diseño.



== Transacción de API de solicitud y respuesta

Cada llamada a la API REST se realiza como una solicitud HTTP al sistema SnapCenter Server que genera una respuesta asociada para el cliente.  Este par de solicitud y respuesta se considera una transacción API.

Antes de utilizar la API, debe familiarizarse con las variables de entrada disponibles para controlar una solicitud y el contenido de la salida de respuesta.



== Soporte para operaciones CRUD

A cada uno de los recursos disponibles a través de la API REST de SnapCenter se accede según el modelo CRUD:

* Crear
* Leer
* Actualizar
* Borrar


Para algunos de los recursos, solo se admite un subconjunto de las operaciones.



== Identificadores de objetos

A cada instancia u objeto de recurso se le asigna un identificador único al crearse. En la mayoría de los casos, el identificador es un UUID de 128 bits.  Estos identificadores son globalmente únicos dentro de un servidor SnapCenter específico.

Después de emitir una llamada API que crea una nueva instancia de objeto, se devuelve al llamador una URL con el ID asociado en el encabezado de ubicación de la respuesta HTTP. Puede extraer el identificador y usarlo en llamadas posteriores al hacer referencia a la instancia del recurso.


IMPORTANT: El contenido y la estructura interna de los identificadores de objeto pueden cambiar en cualquier momento. Solo debe usar los identificadores en las llamadas a la API correspondientes según sea necesario al referirse a los objetos asociados.



== Instancias y colecciones de objetos

Dependiendo de la ruta del recurso y del método HTTP, una llamada API puede aplicarse a una instancia de objeto específica o a una colección de objetos.



== Operaciones sincrónicas y asincrónicas

SnapCenter ejecuta una solicitud HTTP recibida de un cliente de forma sincrónica o asincrónica.



=== Procesamiento sincrónico

SnapCenter ejecuta la solicitud inmediatamente y responde con un código de estado HTTP de 200 o 201 si es exitosa.

Cada solicitud que utiliza el método GET siempre se realiza de forma sincrónica.  Además, las solicitudes que utilizan POST están diseñadas para ejecutarse sincrónicamente si se espera que se completen en menos de dos segundos.



=== Procesamiento asincrónico

Si una solicitud asincrónica es válida, SnapCenter crea una tarea en segundo plano para procesar la solicitud y un objeto de trabajo para anclar la tarea.  El código de estado HTTP 202 se devuelve al llamador junto con el objeto de trabajo.  Debes recuperar el estado del trabajo para determinar el éxito o el fracaso.

Las solicitudes que utilizan los métodos POST y DELETE están diseñadas para ejecutarse de forma asincrónica si se espera que demoren más de dos segundos en completarse.



== Seguridad

La seguridad proporcionada con la API REST se basa principalmente en las funciones de seguridad existentes disponibles con SnapCenter.  La API utiliza la siguiente seguridad:



=== Seguridad de la capa de transporte

Todo el tráfico enviado a través de la red entre el servidor SnapCenter y el cliente normalmente se cifra mediante TLS, según la configuración de SnapCenter .



=== Autenticación HTTP

A nivel HTTP, se utiliza autenticación básica para las transacciones API.  A cada solicitud se agrega un encabezado HTTP con el nombre de usuario y la contraseña en una cadena base64.
