---
sidebar: sidebar 
permalink: sc-automation/concept_input_variables_controlling_an_api_request.html 
keywords: http methods, request headers, request body, filtering objects, size, pagination 
summary: Puede controlar cómo se procesa una llamada API a través de parámetros y variables establecidos en la solicitud HTTP. 
---
= Variables de entrada que controlan una solicitud de API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede controlar cómo se procesa una llamada API a través de parámetros y variables establecidos en la solicitud HTTP.



== Métodos HTTP

Los métodos HTTP compatibles con la API REST de SnapCenter se muestran en la siguiente tabla.


NOTE: No todos los métodos HTTP están disponibles en cada uno de los puntos finales REST.

|===
| Método HTTP | Descripción 


| CONSEGUIR | Recupera propiedades de objeto en una instancia o colección de recursos. 


| CORREO | Crea una nueva instancia de recurso basada en la entrada proporcionada. 


| BORRAR | Elimina una instancia de recurso existente. 


| PONER | Modifica una instancia de recurso existente. 
|===


== Encabezados de solicitud

Debes incluir varios encabezados en la solicitud HTTP.



=== Tipo de contenido

Si el cuerpo de la solicitud incluye JSON, este encabezado debe establecerse como _application/json_.



=== Aceptar

Este encabezado debe establecerse en _application/json_.



=== Autorización

La autenticación básica debe configurarse con el nombre de usuario y la contraseña codificados como una cadena base64.



== Cuerpo de la solicitud

El contenido del cuerpo de la solicitud varía según la llamada específica. El cuerpo de la solicitud HTTP consta de uno de los siguientes elementos:

* Objeto JSON con variables de entrada
* Vacío




== Filtrado de objetos

Al ejecutar una llamada a la API que usa GET, puede limitar o filtrar los objetos devueltos según cualquier atributo. Por ejemplo, puede especificar un valor exacto para que coincida:

`<field>=<query value>`

Además de una coincidencia exacta, hay otros operadores disponibles para devolver un conjunto de objetos en un rango de valores.  La API REST de SnapCenter admite los operadores de filtrado que se muestran en la siguiente tabla.

|===
| Operador | Descripción 


| = | Igual a 


| < | Menos que 


| > | Más que 


| <= | Menor o igual a 


| >= | Mayor o igual que 


| ACTUALIZAR | O 


| ! | No es igual a 


| * | Comodín codicioso 
|===
También puede devolver una colección de objetos en función de si un campo específico está configurado o no utilizando la palabra clave *null* o su negación *!null* como parte de la consulta.


NOTE: Cualquier campo que no esté configurado generalmente se excluye de las consultas coincidentes.



== Solicitar campos de objeto específicos

De forma predeterminada, al ejecutar una llamada a la API mediante GET, solo se devuelven los atributos que identifican de forma única el objeto o los objetos. Este conjunto mínimo de campos actúa como clave para cada objeto y varía según el tipo de objeto. Puede seleccionar propiedades de objeto adicionales utilizando el `fields` parámetro de consulta de las siguientes maneras:



=== Campos comunes o estándar

Especifique *campos=** para recuperar los campos de objeto más utilizados.  Estos campos normalmente se mantienen en la memoria del servidor local o requieren poco procesamiento para acceder a ellos.  Estas son las mismas propiedades devueltas para un objeto después de usar GET con una clave de ruta URL (UUID).



=== Todos los campos

Especifique *fields=*** para recuperar todos los campos del objeto, incluidos aquellos que requieren procesamiento adicional del servidor para acceder.



=== Selección de campo personalizado

Utilice *fields=<field_name>* para especificar el campo exacto que desea. Al solicitar varios campos, los valores deben separarse con comas y sin espacios.


IMPORTANT: Como práctica recomendada, siempre debe identificar los campos específicos que desea. Solo debe recuperar el conjunto de campos comunes o todos los campos cuando sea necesario.  NetApp determina qué campos se clasifican como comunes y se devuelven mediante _fields=*_ basándose en un análisis de rendimiento interno.  La clasificación de un campo podría cambiar en futuras versiones.



== Ordenar objetos en el conjunto de salida

Los registros de una colección de recursos se devuelven en el orden predeterminado definido por el objeto. Puedes cambiar el orden usando el `order_by` parámetro de consulta con el nombre del campo y dirección de clasificación de la siguiente manera:

`order_by=<field name> asc|desc`

Por ejemplo, puede ordenar el campo de tipo en orden descendente seguido de id en orden ascendente:

`order_by=type desc, id asc`

* Si especifica un campo de ordenación pero no proporciona una dirección, los valores se ordenan en orden ascendente.
* Al incluir varios parámetros, debe separar los campos con una coma.




== Paginación al recuperar objetos de una colección

Al emitir una llamada API utilizando GET para acceder a una colección de objetos del mismo tipo, SnapCenter intenta devolver tantos objetos como sea posible en función de dos restricciones.  Puede controlar cada una de estas restricciones utilizando parámetros de consulta adicionales en la solicitud.  La primera restricción alcanzada para una solicitud GET específica finaliza la solicitud y, por lo tanto, limita la cantidad de registros devueltos.


NOTE: Si una solicitud finaliza antes de iterar sobre todos los objetos, la respuesta contiene el enlace necesario para recuperar el siguiente lote de registros.



=== Limitar el número de objetos

De forma predeterminada, SnapCenter devuelve un máximo de 10 000 objetos para una solicitud GET.  Puede cambiar este límite utilizando el parámetro de consulta _max_records_. Por ejemplo:

`max_records=20`

La cantidad de objetos realmente devueltos puede ser menor que el máximo vigente, en función de la restricción de tiempo relacionada, así como de la cantidad total de objetos en el sistema.



=== Limitar el tiempo empleado para recuperar los objetos

De forma predeterminada, SnapCenter devuelve tantos objetos como sea posible dentro del tiempo permitido para la solicitud GET.  El tiempo de espera predeterminado es de 15 segundos.  Puede cambiar este límite utilizando el parámetro de consulta _return_timeout_. Por ejemplo:

`return_timeout=5`

La cantidad de objetos realmente devueltos puede ser menor que el máximo vigente, en función de la restricción relacionada con la cantidad de objetos, así como de la cantidad total de objetos en el sistema.



=== Limitar el conjunto de resultados

Si es necesario, puede combinar estos dos parámetros con parámetros de consulta adicionales para limitar el conjunto de resultados.  Por ejemplo, lo siguiente devuelve hasta 10 eventos EMS generados después del tiempo especificado:

`time=> 2018-04-04T15:41:29.140265Z&max_records=10`

Puede emitir varias solicitudes para navegar por los objetos. Cada llamada a la API posterior debe usar un nuevo valor de tiempo basado en el último evento del último conjunto de resultados.



== Propiedades de tamaño

Los valores de entrada utilizados con algunas llamadas API, así como ciertos parámetros de consulta, son numéricos.  En lugar de proporcionar un número entero en bytes, puede utilizar opcionalmente un sufijo como se muestra en la siguiente tabla.

|===
| Sufijo | Descripción 


| KB | KB Kilobytes (1024 bytes) o kibibytes 


| MEGABYTE | MB Megabytes (KB x 1024 bytes) o mebibytes 


| GB | GB Gigabytes (MB x 1024 bytes) o gibibytes 


| tuberculosis | TB Terabytes (GB x 1024 bytes) o tebibytes 


| PB | PB Petabytes (TB x 1024 bytes) o pebibytes 
|===