---
permalink: sc-automation/task_how to_access_rest_apis_using_the_swagger_api_web_page.html 
sidebar: sidebar 
keywords: REST API, Swagger 
summary: Las API REST se exponen a través de la página web Swagger.  Puede acceder a la página web de Swagger para mostrar las API REST de SnapCenter Server, así como para emitir manualmente una llamada API.  Puede utilizar las API REST para ayudar a administrar su servidor SnapCenter o para realizar operaciones de protección de datos. 
---
= Cómo acceder a las API REST mediante la página web de la API de Swagger
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las API REST se exponen a través de la página web Swagger.  Puede acceder a la página web de Swagger para mostrar las API REST de SnapCenter Server, así como para emitir manualmente una llamada API.  Puede utilizar las API REST para ayudar a administrar su servidor SnapCenter o para realizar operaciones de protección de datos.

Debe conocer la dirección IP de administración o el nombre de dominio del servidor SnapCenter en el que desea ejecutar las API REST.

No necesita permisos especiales para ejecutar el cliente API REST.  Cualquier usuario puede acceder a la página web de Swagger.  Los permisos respectivos sobre los objetos a los que se accede a través de la API REST se basan en el usuario que genera el token para iniciar sesión en la API REST.

.Pasos
. Desde un navegador, ingrese la URL para acceder a la página web de Swagger en el formato _\https://<dirección_IP_o_nombre_de_SnapCenter>:<puerto_de_SnapCenter>/swagger/_.
+

NOTE: Asegúrese de que la URL de la API REST no tenga los siguientes caracteres: +, ., %, y &.

. En el campo *Swagger Explore*, si la documentación de la API de Swagger no se muestra automáticamente, escriba: _\https://<SnapCenter_IP_address_or_name>:<SnapCenter_port>/Content/swagger/ SnapCenter.yaml_
. Haga clic en *Explorar*.
+
Se muestra una lista de tipos o categorías de recursos de API.

. Haga clic en un tipo de recurso de API para mostrar las API en ese tipo de recurso.


Si encuentra un comportamiento inesperado al ejecutar las API REST de SnapCenter , puede usar los archivos de registro para identificar la causa y resolver el problema.  Puede descargar los archivos de registro desde la interfaz de usuario de SnapCenter haciendo clic en *Monitor* > *Registros* > *Descargar*.
