---
permalink: protect-azure/backup-sap-hana-resource-groups.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database, back up, resource groups 
summary: Un grupo de recursos es una colección de recursos en un host.  Se realiza una operación de copia de seguridad en el grupo de recursos en todos los recursos definidos en el grupo de recursos. 
---
= Realizar copias de seguridad de los grupos de recursos de SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un grupo de recursos es una colección de recursos en un host.  Se realiza una operación de copia de seguridad en el grupo de recursos en todos los recursos definidos en el grupo de recursos.

.Pasos
. En el panel de navegación izquierdo, seleccione *Recursos* y luego seleccione el complemento apropiado de la lista.
. En la página Recursos, seleccione *Grupo de recursos* de la lista *Ver*.
. En la página Grupos de recursos, seleccione el grupo de recursos que desea respaldar y luego seleccione *Hacer copia de seguridad ahora*.
. En la página Copia de seguridad, realice los siguientes pasos:
+
.. Si hay varias políticas asociadas al grupo de recursos, en la lista desplegable *Política*, seleccione la política que desea utilizar para la copia de seguridad.
+
Si la política seleccionada para la copia de seguridad a pedido está asociada con una programación de copia de seguridad, las copias de seguridad a pedido se conservarán según la configuración de retención especificada para el tipo de programación.

.. Seleccione *Copia de seguridad*.


. Supervise el progreso de la operación seleccionando *Monitor* > *Trabajos*.

