---
permalink: protect-azure/create-credential-add-plugin-host.html 
sidebar: sidebar 
keywords: snapcenter, azure, credential, plug-in host 
summary: Cree las credenciales para agregar el host del complemento. 
---
= Cree las credenciales para agregar el host del complemento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utiliza credenciales para autenticar a los usuarios para las operaciones de SnapCenter .

Debe crear credenciales para instalar complementos de SnapCenter y credenciales adicionales para realizar operaciones de protección de datos.

.Pasos
. En el panel de navegación izquierdo, haga clic en *Configuración*.
. En la página de Configuración, haga clic en *Credencial*.
. Haga clic en *Nuevo*.
. En la página Credencial, especifique la siguiente información necesaria para crear la credencial.
+
|===
| Para este campo... | Haz esto... 


 a| 
Nombre de la credencial
 a| 
Introduzca un nombre para la credencial.



 a| 
Modo de autenticación
 a| 
Seleccione el modo de autenticación de la lista desplegable.



 a| 
Tipo de autenticación
 a| 
Seleccione *Basado en contraseña* o *Basado en clave SSH* (solo para host Linux).



 a| 
Nombre de usuario
 a| 
Especifique el nombre de usuario.



 a| 
Password
 a| 
Si ha seleccionado la autenticación basada en contraseña, especifique la contraseña.



 a| 
Clave privada SSH
 a| 
Si ha seleccionado la autenticación basada en clave SSH, especifique la clave privada.



 a| 
Utilice privilegios de sudo
 a| 
Seleccione la casilla de verificación Usar privilegios de sudo si está creando credenciales para un usuario que no es root.


NOTE: Esto solo se aplica a usuarios de Linux.

|===
. Haga clic en *Aceptar*.

