---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Cree la credencial de Azure en SnapCenter para acceder a la cuenta de Azure NetApp . 
---
= Crear la credencial de Azure en SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear la credencial de Azure en SnapCenter para acceder a la cuenta de Azure NetApp .

.Antes de empezar
* Asegúrese de haber creado la entidad de servicio en Azure.
* Asegúrese de tener a mano el ID de inquilino, el ID de cliente y la clave secreta asociados con la entidad de servicio.
+
** El identificador de inquilino se puede encontrar en el Portal de Azure, en la página Descripción general del identificador de Entra.
** El ID del cliente también se conoce como ID de la aplicación para la entidad principal del servicio/aplicación empresarial.  Esto se puede encontrar en el Portal de Azure, en la página Descripción general de la aplicación empresarial que ha creado para que actúe como entidad de servicio para SnapCenter.
** La clave secreta del cliente también se conoce como valor secreto.  Puede crear este secreto de cliente en Azure Portal navegando a *Registros de aplicaciones* en ID de entrada.  Después de seleccionar la aplicación empresarial que creó, navegue a *Certificados y secretos* y luego a *Nuevo secreto de cliente*.
+

NOTE: Sólo se puede acceder al valor secreto cuando se crea.  No podrás acceder a él más tarde.

** Es necesario conceder permisos al principal del servicio.  El rol de Colaborador permitirá que la entidad de servicio realice las acciones necesarias en Azure.  Esto se puede conceder desde la página de Control de acceso (IAM) dentro de la página Suscripción.




.Pasos
. En el panel de navegación izquierdo, haga clic en *Configuración*.
. En la página de Configuración, haga clic en *Credencial*.
. Haga clic en *Nuevo*.
. En la página Credencial, especifique la siguiente información necesaria para crear la credencial.
+
|===
| Para este campo... | Haz esto... 


 a| 
Nombre de la credencial
 a| 
Introduzca un nombre para la credencial.



 a| 
Modo de autenticación
 a| 
Seleccione *Credenciales de Azure* de la lista desplegable.



 a| 
Identificación del inquilino
 a| 
Introduzca el ID del inquilino.



 a| 
ID de cliente
 a| 
Introduzca el ID del cliente.



 a| 
Clave secreta del cliente
 a| 
Introduzca la clave secreta del cliente.

|===
. Haga clic en *Aceptar*.

