---
permalink: admin/task_request_status_reports_of_the_jobs_from_the_dashboard.html 
sidebar: sidebar 
keywords: dashboard, snapcenter 
summary: Puede solicitar informes sobre trabajos de copia de seguridad, restauración y clonación desde la página del Panel de control.  Esto es útil si desea identificar la cantidad total de trabajos exitosos o fallidos en su entorno de SnapCenter . 
---
= Solicitar informes de estado de los trabajos desde el panel de control
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede solicitar informes sobre trabajos de copia de seguridad, restauración y clonación desde la página del Panel de control.  Esto es útil si desea identificar la cantidad total de trabajos exitosos o fallidos en su entorno de SnapCenter .

*Pasos*

. En el panel de navegación izquierdo, haga clic en *Panel de control*
. Localice el mosaico Trabajos en el Panel de Control y luego seleccione *Copia de Seguridad*, *Restaurar* o *Clonar*.
. Utilizando el menú desplegable, seleccione el período de tiempo para el cual desea información de trabajos: 24 horas, 7 días o 30 días.
+
Los sistemas muestran un gráfico de anillos que cubre los datos.

. Haga clic en el segmento de dona que representa la información del trabajo para el cual desea un informe.
+
Al hacer clic en el gráfico de anillos, se le redirige de la página del Panel a la página del Monitor.  La página Monitor muestra los trabajos con el estado seleccionado en el gráfico de anillos.

. Desde la lista de la página Monitor, haga clic en un trabajo específico para seleccionarlo.
. En la parte superior de la página Monitor, haga clic en *Informes*.


*Resultado*

El informe muestra información únicamente para el trabajo seleccionado.  Puede revisar el informe o descargarlo a su sistema local.
