---
permalink: install/concept_svm_connections_and_credentials.html 
sidebar: sidebar 
keywords: storage, connection, credentials 
summary: Antes de realizar operaciones de protección de datos, debe configurar las conexiones de almacenamiento y agregar las credenciales que usarán SnapCenter Server y los complementos de SnapCenter . 
---
= Conexiones de almacenamiento y credenciales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de realizar operaciones de protección de datos, debe configurar las conexiones de almacenamiento y agregar las credenciales que usarán SnapCenter Server y los complementos de SnapCenter .



== Conexiones de almacenamiento

Las conexiones de almacenamiento brindan a SnapCenter Server y a los complementos de SnapCenter acceso al almacenamiento de ONTAP .  La configuración de estas conexiones también implica configurar las funciones de AutoSupport y del Sistema de gestión de eventos (EMS).



== Cartas credenciales

* Administrador del dominio o cualquier miembro del grupo de administradores
+
Especifique el administrador del dominio o cualquier miembro del grupo de administradores del sistema donde va a instalar el complemento de SnapCenter . Los formatos válidos para el campo Nombre de usuario son:

+
** _NetBIOS\Nombre de usuario_
** _Dominio FQDN\Nombre de usuario_
** _Nombre de usuario@upn_


* Administrador local (sólo para grupos de trabajo)
+
Para los sistemas que pertenecen a un grupo de trabajo, especifique el administrador local integrado en el sistema donde va a instalar el complemento de SnapCenter . Puede especificar una cuenta de usuario local que pertenezca al grupo de administradores locales si esta cuenta tiene privilegios elevados o si la función de control de acceso de usuario está deshabilitada en el sistema host.

+
El formato válido para el campo Nombre de usuario es: _NombreDeUsuario_

* Credenciales para grupos de recursos individuales
+
Si configura credenciales para grupos de recursos individuales y el nombre de usuario no tiene privilegios de administrador completos, debe asignar al menos los privilegios de grupo de recursos y de respaldo al nombre de usuario.


