---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate 
summary: Debe configurar el certificado CA con el sitio SnapCenter en el host de Windows. 
---
= Configurar el certificado de CA con el sitio de SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar el certificado CA con el sitio SnapCenter en el host de Windows.

*Pasos*

. Abra el Administrador de IIS en el servidor Windows donde está instalado SnapCenter .
. En el panel de navegación izquierdo, haga clic en *Conexiones*.
. Amplíe el nombre del servidor y *Sitios*.
. Seleccione el sitio web de SnapCenter en el que desea instalar el certificado SSL.
. Vaya a *Acciones* > *Editar sitio* y haga clic en *Enlaces*.
. En la página Enlaces, seleccione *enlace para https*.
. Haga clic en *Editar*.
. En la lista desplegable del certificado SSL, seleccione el certificado SSL importado recientemente.
. Haga clic en *Aceptar*.
+

NOTE: El sitio del Programador de SnapCenter (puerto predeterminado: 8154, HTTPS) está configurado con un certificado autofirmado.  Este puerto se comunica dentro del host del servidor SnapCenter y no es obligatorio configurarlo con un certificado CA.  Sin embargo, si su entorno le exige utilizar un certificado CA, repita los pasos 5 a 9 utilizando el sitio del Programador de SnapCenter .




NOTE: Si el certificado CA implementado recientemente no aparece en el menú desplegable, verifique si el certificado CA está asociado con la clave privada.


IMPORTANT: Asegúrese de que el certificado se agregue mediante la siguiente ruta: *Raíz de consola > Certificados – Equipo local > Autoridades de certificación raíz de confianza > Certificados*.
