---
permalink: install/task_reclaim_space_on_the_storage_system.html 
sidebar: sidebar 
keywords: space, storage system, reclaim 
summary: Aunque NTFS rastrea el espacio disponible en un LUN cuando se eliminan o modifican archivos, no informa la nueva información al sistema de almacenamiento.  Puede ejecutar el cmdlet de PowerShell de recuperación de espacio en el host del complemento para Windows para garantizar que los bloques recién liberados se marquen como disponibles en el almacenamiento. 
---
= Recuperar espacio en el sistema de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aunque NTFS rastrea el espacio disponible en un LUN cuando se eliminan o modifican archivos, no informa la nueva información al sistema de almacenamiento.  Puede ejecutar el cmdlet de PowerShell de recuperación de espacio en el host del complemento para Windows para garantizar que los bloques recién liberados se marquen como disponibles en el almacenamiento.

Si está ejecutando el cmdlet en un host de complemento remoto, debe haber ejecutado el cmdlet SnapCenterOpen-SMConnection para abrir una conexión al servidor SnapCenter .

.Antes de empezar
* Debe asegurarse de que el proceso de recuperación de espacio se haya completado antes de realizar una operación de restauración.
* Si el LUN es compartido por los hosts en un clúster de conmutación por error de Windows Server, debe realizar una recuperación de espacio en el host que posee el grupo de clústeres.
* Para obtener un rendimiento de almacenamiento óptimo, debe realizar la recuperación de espacio con la mayor frecuencia posible.
+
Debe asegurarse de que se haya escaneado todo el sistema de archivos NTFS.



*Acerca de esta tarea*

* La recuperación de espacio consume mucho tiempo y consume muchos recursos de la CPU, por lo que generalmente es mejor ejecutar la operación cuando el uso del sistema de almacenamiento y del host de Windows es bajo.
* La recuperación de espacio recupera casi todo el espacio disponible, pero no el 100 por ciento.
* No debe ejecutar la desfragmentación del disco al mismo tiempo que realiza la recuperación de espacio.
+
Hacerlo puede ralentizar el proceso de recuperación.



*Paso*

Desde el símbolo del sistema de PowerShell del servidor de aplicaciones, ingrese el siguiente comando:

`Invoke-SdHostVolumeSpaceReclaim -Path drive_path`

drive_path es la ruta de la unidad asignada al LUN.
