---
permalink: install/task_enable_two_way_ssl.html 
sidebar: sidebar 
keywords: security,disable two-way SSL,enable two-way SSL, windows host 
summary: Puede habilitar la comunicación SSL bidireccional para proteger la comunicación mutua entre SnapCenter Server en el host de Windows y los complementos mediante comandos de PowerShell. 
---
= Habilitar la comunicación SSL bidireccional en el host de Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar la comunicación SSL bidireccional para proteger la comunicación mutua entre SnapCenter Server en el host de Windows y los complementos mediante comandos de PowerShell.

*Antes de empezar*

Ejecute primero los comandos para todos los complementos y el agente SMCore y luego para el servidor.

*Pasos*

. Para habilitar la comunicación SSL bidireccional, ejecute los siguientes comandos en el servidor SnapCenter para los complementos, el servidor y para cada uno de los agentes para los que se requiere la comunicación SSL bidireccional.
+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="true"} -HostName <Plugin_HostName>`

+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="true"} -HostName localhost`

+
`> Set-SmConfigSettings -Server -configSettings @{"EnableTwoWaySSL"="true"}`

. Realice la operación de reciclaje del grupo de aplicaciones de IIS SnapCenter mediante el siguiente comando.
`> Restart-WebAppPool -Name "SnapCenter"`
. Para los complementos de Windows, reinicie el servicio SMCore ejecutando el siguiente comando de PowerShell:
+
`> Restart-Service -Name SnapManagerCoreService`





== Deshabilitar la comunicación SSL bidireccional

Puede deshabilitar la comunicación SSL bidireccional mediante comandos de PowerShell.

*Acerca de esta tarea*

* Ejecute primero los comandos para todos los complementos y el agente SMCore y luego para el servidor.
* Al deshabilitar la comunicación SSL bidireccional, el certificado CA y su configuración no se eliminan.
* Para agregar un nuevo host a SnapCenter Server, debe deshabilitar el SSL bidireccional para todos los hosts del complemento.
* NLB y F5 no son compatibles.


*Pasos*

. Para deshabilitar la comunicación SSL bidireccional, ejecute los siguientes comandos en SnapCenter Server para todos los hosts del complemento y el host de SnapCenter .
+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="false"} -HostName <Agent_HostName>`

+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="false"} -HostName localhost`

+
`> Set-SmConfigSettings -Server -configSettings @{"EnableTwoWaySSL"="false"}`

. Realice la operación de reciclaje del grupo de aplicaciones de IIS SnapCenter mediante el siguiente comando.
`> Restart-WebAppPool -Name "SnapCenter"`
. Para los complementos de Windows, reinicie el servicio SMCore ejecutando el siguiente comando de PowerShell:
+
`> Restart-Service -Name SnapManagerCoreService`


