---
permalink: install/task_configure_CA_client_certificate_for_LDAPS.html 
sidebar: sidebar 
keywords: CA client certificate, LDAPS 
summary: Debe configurar el certificado de cliente de CA para LDAPS en el servidor SnapCenter cuando LDAPS de Windows Active Directory esté configurado con los certificados de CA. 
---
= Configurar el certificado de cliente de CA para LDAPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar el certificado de cliente de CA para LDAPS en el servidor SnapCenter cuando LDAPS de Windows Active Directory esté configurado con los certificados de CA.

*Pasos*

. Vaya a la consola de administración de Microsoft (MMC) y haga clic en *Archivo* > *Agregar o quitar complemento*.
. En la ventana Agregar o quitar complementos, seleccione *Certificados* y luego haga clic en *Agregar*.
. En la ventana del complemento Certificados, seleccione la opción *Cuenta de equipo* y haga clic en *Finalizar*.
. Haga clic en *Consola raíz* > *Certificados – Equipo local* > *Autoridades de certificación raíz de confianza* > *Certificados*.
. Haga clic con el botón derecho en la carpeta “Autoridades de certificación raíz de confianza” y luego seleccione *Todas las tareas* > *Importar* para iniciar el asistente de importación.
. Complete el asistente de la siguiente manera:
+
|===
| En esta ventana del asistente... | Haz lo siguiente... 


 a| 
En la segunda página del asistente
 a| 
Haga clic en *Explorar*, seleccione el _Certificado raíz_ y haga clic en *Siguiente*.



 a| 
Cómo completar el Asistente para importar certificados
 a| 
Revise el resumen y luego haga clic en *Finalizar* para iniciar la importación.

|===
. Repita los pasos 5 y 6 para los certificados intermedios.

