---
permalink: install/task_export_ca_certificates_from_snapcenter_server.html 
sidebar: sidebar 
keywords: security,authentication, export CA certificates 
summary: Debe exportar los certificados de CA desde el servidor SnapCenter a los hosts del complemento. 
---
= Exportar certificados de autoridad de certificación (CA) desde SnapCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe exportar los certificados de CA desde el servidor SnapCenter a los hosts del complemento mediante la consola de administración de Microsoft (MMC).

.Antes de empezar
Deberías haber configurado el SSL bidireccional.

*Pasos*

. Vaya a la consola de administración de Microsoft (MMC) y haga clic en *Archivo* > *Agregar o quitar complemento*.
. En la ventana Agregar o quitar complementos, seleccione *Certificados* y luego haga clic en *Agregar*.
. En la ventana Complemento de certificados, seleccione la opción *Cuenta de equipo* y haga clic en *Finalizar*.
. Haga clic en *Raíz de consola* > *Certificados - Equipo local* > *Personal* > *Certificados*.
. Haga clic con el botón derecho en el certificado CA adquirido, que se utiliza para SnapCenter Server y luego seleccione *Todas las tareas* > *Exportar* para iniciar el asistente de exportación.
. Realice las siguientes acciones en el asistente.


|===
| Para esta opción... | Haz lo siguiente... 


 a| 
Exportar clave privada
 a| 
Seleccione *No, no exportar la clave privada* y luego haga clic en *Siguiente*.



 a| 
Formato de archivo de exportación
 a| 
Haga clic en *Siguiente*.



 a| 
Nombre del archivo
 a| 
Haga clic en *Explorar* y especifique la ruta del archivo para guardar el certificado y haga clic en *Siguiente*.



 a| 
Cómo completar el Asistente para exportar certificados
 a| 
Revise el resumen y luego haga clic en *Finalizar* para iniciar la exportación.

|===

NOTE: La autenticación basada en certificados no es compatible con las configuraciones de SnapCenter HA ni con el SnapCenter Plug-in for VMware vSphere.
