---
permalink: install/task_add_storage_systems.html 
sidebar: sidebar 
keywords: add, storage system, SVM, ASA r2 systems 
summary: Debe configurar el sistema de almacenamiento que le otorga a SnapCenter acceso al almacenamiento ONTAP para realizar operaciones de aprovisionamiento y protección de datos.  Puede agregar un SVM independiente o un clúster compuesto por varios SVM. 
---
= Añadir sistemas de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar el sistema de almacenamiento que le otorga a SnapCenter acceso al almacenamiento ONTAP , a los sistemas ASA r2 o a Amazon FSx for NetApp ONTAP para realizar operaciones de aprovisionamiento y protección de datos.

Puede agregar un SVM independiente o un clúster compuesto por varios SVM.  Si está utilizando Amazon FSx for NetApp ONTAP, puede agregar un LIF de administrador de FSx que comprenda múltiples SVM mediante la cuenta fsxadmin o agregar FSx SVM en SnapCenter.

.Antes de empezar
* Debe tener los permisos necesarios en el rol de administrador de infraestructura para crear conexiones de almacenamiento.
* Debe asegurarse de que las instalaciones del complemento no estén en curso.
+
Las instalaciones de complementos de host no deben estar en progreso mientras se agrega una conexión al sistema de almacenamiento porque es posible que la memoria caché del host no se actualice y el estado de las bases de datos puede mostrarse en la GUI de SnapCenter como "`No disponible para respaldo`" o "`No en almacenamiento de NetApp ".

* Los nombres de los sistemas de almacenamiento deben ser únicos.
+
SnapCenter no admite varios sistemas de almacenamiento con el mismo nombre en diferentes clústeres.  Cada sistema de almacenamiento compatible con SnapCenter debe tener un nombre único y una dirección IP LIF de datos única.



*Acerca de esta tarea*

* Al configurar sistemas de almacenamiento, también puede habilitar las funciones del Sistema de administración de eventos (EMS) y AutoSupport .  La herramienta AutoSupport recopila datos sobre el estado de su sistema y envía automáticamente dichos datos al soporte técnico de NetApp , lo que les permite solucionar problemas de su sistema.
+
Si habilita estas funciones, SnapCenter envía información de AutoSupport al sistema de almacenamiento y mensajes EMS al syslog del sistema de almacenamiento cuando un recurso está protegido, una operación de restauración o clonación finaliza correctamente o una operación falla.

* Si planea replicar instantáneas a un destino SnapMirror o SnapVault , debe configurar conexiones del sistema de almacenamiento para la SVM o el clúster de destino, así como para la SVM o el clúster de origen.



NOTE: Si cambia la contraseña del sistema de almacenamiento, es posible que fallen los trabajos programados, las copias de seguridad a pedido y las operaciones de restauración.  Después de cambiar la contraseña del sistema de almacenamiento, puede actualizarla haciendo clic en *Modificar* en la pestaña Almacenamiento.

*Pasos*

. En el panel de navegación izquierdo, haga clic en *Sistemas de almacenamiento*.
. En la página Sistemas de almacenamiento, haga clic en *Nuevo*.
. En la página Agregar sistema de almacenamiento, proporcione la siguiente información:
+
|===
| Para este campo... | Haz esto... 


 a| 
Sistema de almacenamiento
 a| 
Introduzca el nombre del sistema de almacenamiento o la dirección IP.


NOTE: Los nombres de los sistemas de almacenamiento, sin incluir el nombre de dominio, deben tener 15 caracteres o menos y deben poder resolverse.  Para crear conexiones del sistema de almacenamiento con nombres que tengan más de 15 caracteres, puede usar el cmdlet Add-SmStorageConnectionPowerShell.


NOTE: Para los sistemas de almacenamiento con configuración MetroCluster (MCC), se recomienda registrar clústeres locales y pares para operaciones sin interrupciones.

SnapCenter no admite varias SVM con el mismo nombre en diferentes clústeres.  Cada SVM compatible con SnapCenter debe tener un nombre único.


NOTE: Después de agregar la conexión de almacenamiento a SnapCenter, no debe cambiar el nombre de la SVM o el clúster mediante ONTAP.


NOTE: Si se agrega SVM con un nombre corto o FQDN, debe poder resolverse tanto desde SnapCenter como desde el host del complemento.



 a| 
Nombre de usuario/Contraseña
 a| 
Ingrese las credenciales del usuario de almacenamiento que tiene los privilegios necesarios para acceder al sistema de almacenamiento.



 a| 
Configuración del sistema de gestión de eventos (EMS) y AutoSupport
 a| 
Si desea enviar mensajes EMS al syslog del sistema de almacenamiento o si desea que se envíen mensajes de AutoSupport al sistema de almacenamiento para protección aplicada, operaciones de restauración completadas u operaciones fallidas, seleccione la casilla de verificación correspondiente.

Cuando selecciona la casilla de verificación *Enviar notificación de AutoSupport para operaciones fallidas al sistema de almacenamiento*, la casilla de verificación *Registrar eventos del servidor SnapCenter en syslog* también se selecciona porque se requieren mensajes EMS para habilitar las notificaciones de AutoSupport .

|===
. Haga clic en *Más opciones* si desea modificar los valores predeterminados asignados a la plataforma, el protocolo, el puerto y el tiempo de espera.
+
.. En Plataforma, seleccione una de las opciones de la lista desplegable.
+
Si el SVM es el sistema de almacenamiento secundario en una relación de respaldo, seleccione la casilla de verificación *Secundario*.  Cuando se selecciona la opción *Secundaria*, SnapCenter no realiza una verificación de licencia inmediatamente.

+
Si ha agregado SVM en SnapCenter , el usuario deberá seleccionar manualmente el tipo de plataforma en el menú desplegable.

.. En Protocolo, seleccione el protocolo que se configuró durante la configuración de SVM o del clúster, normalmente HTTPS.
.. Introduzca el puerto que acepta el sistema de almacenamiento.
+
El puerto predeterminado 443 normalmente funciona.

.. Introduzca el tiempo en segundos que debe transcurrir antes de que se detengan los intentos de comunicación.
+
El valor predeterminado es 60 segundos.

.. Si el SVM tiene múltiples interfaces de administración, seleccione la casilla de verificación *IP preferida* y luego ingrese la dirección IP preferida para las conexiones SVM.
.. Haga clic en *Guardar*.


. Haga clic en *Enviar*.


*Resultado*

En la página Sistemas de almacenamiento, desde el menú desplegable *Tipo*, realice una de las siguientes acciones:

* Seleccione * ONTAP SVMs* si desea ver todas las SVM que se agregaron.
+
Si ha agregado SVM de FSx, estos se enumeran aquí.

* Seleccione * Clústeres ONTAP * si desea ver todos los clústeres que se agregaron.
+
Si ha agregado clústeres FSx mediante fsxadmin, los clústeres FSx se enumeran aquí.

+
Al hacer clic en el nombre del clúster, todas las SVM que forman parte del clúster se muestran en la sección Máquinas virtuales de almacenamiento.

+
Si se agrega una nueva SVM al clúster ONTAP mediante la GUI de ONTAP , haga clic en *Redescubrir* para ver la SVM recién agregada.



*Después de terminar*

Un administrador de clúster debe habilitar AutoSupport en cada nodo del sistema de almacenamiento para enviar notificaciones por correo electrónico desde todos los sistemas de almacenamiento a los que SnapCenter tiene acceso, ejecutando el siguiente comando desde la línea de comandos del sistema de almacenamiento:

`autosupport trigger modify -node nodename -autosupport-message client.app.info -to enable -noteto enable`


NOTE: El administrador de la máquina virtual de almacenamiento (SVM) no tiene acceso a AutoSupport.
