---
permalink: protect-scu/reference_prepare_for_protecting_UNIX file systems.html 
sidebar: sidebar 
keywords: unix file systems, preparation for protection, prerequisites 
summary: Antes de realizar cualquier operación de protección de datos, como copias de seguridad, clonación o restauración, debe configurar su entorno. 
---
= Prepárese para proteger los sistemas de archivos Unix
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de realizar cualquier operación de protección de datos, como copias de seguridad, clonación o restauración, debe configurar su entorno.  También puede configurar el servidor SnapCenter para utilizar la tecnología SnapMirror y SnapVault .

Para aprovechar la tecnología SnapVault y SnapMirror , debe configurar e inicializar una relación de protección de datos entre los volúmenes de origen y destino en el dispositivo de almacenamiento.  Puede utilizar NetAppSystem Manager o puede utilizar la línea de comandos de la consola de almacenamiento para realizar estas tareas.

Antes de utilizar el complemento para sistemas de archivos Unix, el administrador de SnapCenter debe instalar y configurar el servidor SnapCenter y realizar las tareas previas requeridas.

* Instalar y configurar SnapCenter Server.link:../install/task_install_the_snapcenter_server_using_the_install_wizard.html["Más información"^]
* Configure el entorno de SnapCenter agregando conexiones del sistema de almacenamiento.link:../install/task_add_storage_systems.html["Más información"^]
+

NOTE: SnapCenter no admite varias SVM con el mismo nombre en diferentes clústeres.  Cada SVM registrado con SnapCenter mediante el registro SVM o el registro de clúster debe ser único.

* Agregue hosts, instale los complementos y descubra los recursos.
* Si utiliza SnapCenter Server para proteger sistemas de archivos Unix que residen en LUN o VMDK de VMware RDM, debe implementar el SnapCenter Plug-in for VMware vSphere y registrar el complemento con SnapCenter.
* Instale Java en su host Linux.
* Configure SnapMirror y SnapVault en ONTAP, si desea replicación de copia de seguridad.

