---
permalink: protect-scu/task_configure_snapcenter_plug_in_loader_service.html 
sidebar: sidebar 
keywords: SPL, plug-in loader service 
summary: El servicio SnapCenter Plug-in Loader carga el paquete de complementos para Linux para interactuar con el servidor SnapCenter .  El servicio SnapCenter Plug-in Loader se instala cuando instala el paquete de complementos de SnapCenter para Linux. 
---
= Configurar el servicio de Loader de complementos de SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El servicio SnapCenter Plug-in Loader carga el paquete de complementos para Linux para interactuar con el servidor SnapCenter .  El servicio SnapCenter Plug-in Loader se instala cuando instala el paquete de complementos de SnapCenter para Linux.

*Acerca de esta tarea*

Después de instalar el paquete de complementos de SnapCenter para Linux, el servicio SnapCenter Plug-in Loader se inicia automáticamente.  Si el servicio SnapCenter Plug-in Loader no se inicia automáticamente, debe:

* Asegúrese de que el directorio donde está funcionando el complemento no se elimine
* Aumentar el espacio de memoria asignado a la máquina virtual Java


El archivo spl.properties, que se encuentra en _/custom_location/ NetApp/snapcenter/spl/etc/_, contiene los siguientes parámetros.  A estos parámetros se les asignan valores predeterminados.

|===
| Nombre del parámetro | Descripción 


 a| 
NIVEL DE REGISTRO
 a| 
Muestra los niveles de registro admitidos.

Los valores posibles son TRACE, DEBUG, INFO, WARN, ERROR y FATAL.



 a| 
PROTOCOLO SPL
 a| 
Muestra el protocolo compatible con SnapCenter Plug-in Loader.

Sólo se admite el protocolo HTTPS.  Puede agregar el valor si falta el valor predeterminado.



 a| 
PROTOCOLO DEL SERVIDOR SNAPCENTER
 a| 
Muestra el protocolo compatible con SnapCenter Server.

Sólo se admite el protocolo HTTPS.  Puede agregar el valor si falta el valor predeterminado.



 a| 
SALTAR ACTUALIZACIÓN DE JAVAHOME
 a| 
De forma predeterminada, el servicio SPL detecta la ruta de Java y actualiza el parámetro JAVA_HOME.

Por lo tanto, el valor predeterminado se establece en FALSO.  Puede establecerlo en VERDADERO si desea deshabilitar el comportamiento predeterminado y corregir manualmente la ruta de Java.



 a| 
CONTRASEÑA DEL ALMACÉN DE LLAVES SPL
 a| 
Muestra la contraseña del archivo del almacén de claves.

Puede cambiar este valor solo si cambia la contraseña o crea un nuevo archivo de almacén de claves.



 a| 
SPL_PORT
 a| 
Muestra el número de puerto en el que se ejecuta el servicio SnapCenter Plug-in Loader .

Puede agregar el valor si falta el valor predeterminado.


NOTE: No debe cambiar el valor después de instalar los complementos.



 a| 
HOST DEL SERVIDOR SNAPCENTER
 a| 
Muestra la dirección IP o el nombre de host del servidor SnapCenter .



 a| 
RUTA DEL ALMACÉN DE LLAVES SPL
 a| 
Muestra la ruta absoluta del archivo del almacén de claves.



 a| 
PUERTO DEL SERVIDOR SNAPCENTER
 a| 
Muestra el número de puerto en el que se ejecuta el servidor SnapCenter .



 a| 
CONTEO MÁXIMO DE REGISTROS
 a| 
Muestra la cantidad de archivos de registro del Loader de complementos de SnapCenter que se conservan en la carpeta _/custom_location/snapcenter/spl/logs_.

El valor predeterminado se establece en 5000.  Si el recuento es mayor que el valor especificado, se conservan los últimos 5000 archivos modificados.  La verificación de la cantidad de archivos se realiza automáticamente cada 24 horas desde que se inicia el servicio SnapCenter Plug-in Loader .


NOTE: Si elimina manualmente el archivo spl.properties, la cantidad de archivos que se conservarán se establecerá en 9999.



 a| 
JAVA_HOME
 a| 
Muestra la ruta absoluta del directorio JAVA_HOME que se utiliza para iniciar el servicio SPL.

Esta ruta se determina durante la instalación y como parte del inicio de SPL.



 a| 
TAMAÑO MÁXIMO DE REGISTRO
 a| 
Muestra el tamaño máximo del archivo de registro de trabajo.

Una vez que se alcanza el tamaño máximo, el archivo de registro se comprime y los registros se escriben en el nuevo archivo de ese trabajo.



 a| 
RETENCIÓN DE REGISTROS DE LOS ÚLTIMOS DÍAS
 a| 
Muestra el número de días que se conservan los registros.



 a| 
HABILITAR VALIDACIÓN DE CERTIFICADO
 a| 
Se muestra como verdadero cuando la validación del certificado CA está habilitada para el host.

Puede habilitar o deshabilitar este parámetro editando spl.properties o utilizando la GUI o el cmdlet de SnapCenter .

|===
Si alguno de estos parámetros no está asignado al valor predeterminado o si desea asignar o cambiar el valor, puede modificar el archivo spl.properties.  También puede verificar el archivo spl.properties y editarlo para solucionar cualquier problema relacionado con los valores asignados a los parámetros.  Después de modificar el archivo spl.properties, debe reiniciar el servicio SnapCenter Plug-in Loader .

*Pasos*

. Realice una de las siguientes acciones, según sea necesario:
+
** Inicie el servicio SnapCenter Plug-in Loader :
+
*** Como usuario root, ejecute: `/custom_location/NetApp/snapcenter/spl/bin/spl start`
*** Como usuario no root, ejecute: `sudo /custom_location/NetApp/snapcenter/spl/bin/spl start`


** Detener el servicio de Loader de complementos de SnapCenter :
+
*** Como usuario root, ejecute: `/custom_location/NetApp/snapcenter/spl/bin/spl stop`
*** Como usuario no root, ejecute: `sudo /custom_location/NetApp/snapcenter/spl/bin/spl stop`
+

NOTE: Puede utilizar la opción -force con el comando stop para detener a la fuerza el servicio SnapCenter Plug-in Loader .  Sin embargo, debe tener cuidado antes de hacerlo porque también termina las operaciones existentes.



** Reinicie el servicio del Loader de complementos de SnapCenter :
+
*** Como usuario root, ejecute: `/custom_location/NetApp/snapcenter/spl/bin/spl restart`
*** Como usuario no root, ejecute: `sudo /custom_location/NetApp/snapcenter/spl/bin/spl restart`


** Encuentre el estado del servicio Loader de complementos de SnapCenter :
+
*** Como usuario root, ejecute: `/custom_location/NetApp/snapcenter/spl/bin/spl status`
*** Como usuario no root, ejecute: `sudo /custom_location/NetApp/snapcenter/spl/bin/spl status`


** Encuentre el cambio en el servicio SnapCenter Plug-in Loader :
+
*** Como usuario root, ejecute: `/custom_location/NetApp/snapcenter/spl/bin/spl change`
*** Como usuario no root, ejecute: `sudo /custom_location/NetApp/snapcenter/spl/bin/spl change`





