---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: Cree una política de respaldo para los sistemas de archivos Unix que desea respaldar. 
---
= Crear políticas de respaldo para sistemas de archivos Unix
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de utilizar SnapCenter para realizar copias de seguridad de sistemas de archivos Unix, debe crear una política de copia de seguridad para el recurso o el grupo de recursos que desea respaldar.  Una política de copias de seguridad es un conjunto de reglas que rigen cómo administrar, programar y conservar las copias de seguridad.  También puede especificar la configuración de replicación, script y tipo de copia de seguridad.  La creación de una política ahorra tiempo cuando desea reutilizarla en otro recurso o grupo de recursos.

.Antes de empezar
* Debe estar preparado para la protección de datos completando tareas como instalar SnapCenter, agregar hosts, descubrir los sistemas de archivos y crear conexiones del sistema de almacenamiento.
* Si está replicando instantáneas en un espejo o almacenamiento secundario de bóveda, el administrador de SnapCenter debe haberle asignado las SVM para los volúmenes de origen y destino.
* Revise los requisitos previos y las limitaciones específicos de la sincronización activa de SnapMirror . Para obtener información, consulte https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Límites de objetos para la sincronización activa de SnapMirror"] .


.Acerca de esta tarea
* SnapLock
+
** Si se selecciona la opción 'Conservar las copias de seguridad durante una cantidad específica de días', el período de retención de SnapLock debe ser menor o igual a los días de retención mencionados.
+
Al especificar un período de bloqueo de instantáneas se evita la eliminación de las instantáneas hasta que expire el período de retención. Esto podría llevar a retener una cantidad mayor de instantáneas que la cantidad especificada en la política.

+
Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de SnapLock Vault como parte de la restauración heredarán el tiempo de vencimiento de SnapLock Vault. El administrador de almacenamiento debe limpiar manualmente los clones después del tiempo de vencimiento de SnapLock .





.Pasos
. En el panel de navegación izquierdo, haga clic en *Configuración*.
. En la página de Configuración, haga clic en *Políticas*.
. Seleccione *Sistemas de archivos Unix* de la lista desplegable.
. Haga clic en *Nuevo*.
. En la página Nombre, ingrese el nombre y los detalles de la política.
. En la página Copia de seguridad y replicación, realice las siguientes acciones:
+
.. Especifique la configuración de la copia de seguridad.
.. Especifique la frecuencia de programación seleccionando *A pedido*, *Cada hora*, *Diariamente*, *Semanalmente* o *Mensualmente*.
.. En la sección Seleccionar opciones de replicación secundaria, seleccione una o ambas de las siguientes opciones de replicación secundaria:


+
|===
| Para este campo... | Haz esto... 


 a| 
Actualizar SnapMirror después de crear una copia de Snapshot local
 a| 
Seleccione este campo para crear copias reflejadas de los conjuntos de copias de seguridad en otro volumen (replicación SnapMirror ).

Esta opción debe estar habilitada para la sincronización activa de SnapMirror .



 a| 
Actualizar SnapVault después de crear una copia de instantánea local
 a| 
Seleccione esta opción para realizar la replicación de copia de seguridad de disco a disco (copias de seguridad de SnapVault ).



 a| 
Recuento de reintentos de error
 a| 
Introduzca el número máximo de intentos de replicación que se pueden permitir antes de que se detenga la operación.

|===
. En la página Retención, especifique la configuración de retención para el tipo de copia de seguridad y el tipo de programación seleccionados en la página Copia de seguridad y replicación:
+
|===


| Si quieres... | Entonces... 


 a| 
Mantenga una cierta cantidad de instantáneas
 a| 
Seleccione *Copias para conservar* y luego especifique la cantidad de instantáneas que desea conservar.

Si el número de instantáneas excede el número especificado, las instantáneas se eliminan primero, comenzando por las copias más antiguas.


NOTE: El valor máximo de retención es 1018. Las copias de seguridad fallarán si la retención se establece en un valor superior al que admite la versión subyacente de ONTAP .


IMPORTANT: Debe establecer el recuento de retención en 2 o más si planea habilitar la replicación de SnapVault .  Si establece el recuento de retención en 1, la operación de retención puede fallar porque la primera instantánea es la instantánea de referencia para la relación SnapVault hasta que se replique una instantánea más nueva en el destino.



 a| 
Conservar las instantáneas durante un número determinado de días
 a| 
Seleccione *Conservar copias durante* y, a continuación, especifique la cantidad de días durante los cuales desea conservar las instantáneas antes de eliminarlas.



 a| 
Período de bloqueo de copia de instantánea
 a| 
Seleccione *Período de bloqueo de copia de instantánea* y especifique la duración en días, meses o años.

El período de retención del Snaplock debe ser inferior a 100 años.

|===
. Seleccione la etiqueta de la política.
+

NOTE: Puede asignar etiquetas SnapMirror a instantáneas principales para replicación remota, lo que permite que las instantáneas principales descarguen la operación de replicación de instantáneas de SnapCenter a los sistemas secundarios de ONTAP . Esto se puede hacer sin habilitar la opción SnapMirror o SnapVault en la página de políticas.

. En la página Script, ingrese la ruta y los argumentos del prescript o postscript que desea ejecutar antes o después de la operación de respaldo, respectivamente.
+

NOTE: Debe verificar si los comandos existen en la lista de comandos disponible en el host del complemento desde la ruta _ /opt/ NetApp/snapcenter/scc/etc/allowed_commands.config_.

+
También puede especificar el valor de tiempo de espera del script. El valor predeterminado es 60 segundos.

. Revise el resumen y luego haga clic en *Finalizar*.

