---
permalink: protect-db2/create-a-storage-system-connection-and-a-run-as-account-using-powershell-cmdlets-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 'Debe crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar los cmdlets de PowerShell para realizar copias de seguridad, restaurar o clonar bases de datos de IBM Db2.' 
---
= Cree una conexión al sistema de almacenamiento y una credencial mediante cmdlets de PowerShell para IBM Db2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar los cmdlets de PowerShell para realizar copias de seguridad, restaurar o clonar bases de datos de IBM Db2.

.Antes de empezar
* Debería haber preparado el entorno de PowerShell para ejecutar los cmdlets de PowerShell.
* Debe tener los permisos necesarios en el rol de administrador de infraestructura para crear conexiones de almacenamiento.
* Debe asegurarse de que las instalaciones del complemento no estén en curso.
+
Las instalaciones de complementos de host no deben estar en progreso mientras se agrega una conexión al sistema de almacenamiento porque es posible que la memoria caché del host no se actualice y el estado de las bases de datos puede mostrarse en la GUI de SnapCenter como "`No disponible para respaldo`" o "`No en almacenamiento de NetApp ".

* Los nombres de los sistemas de almacenamiento deben ser únicos.
+
SnapCenter no admite varios sistemas de almacenamiento con el mismo nombre en diferentes clústeres.  Cada sistema de almacenamiento compatible con SnapCenter debe tener un nombre único y una dirección IP LIF de datos única.



.Pasos
. Haga clic en *SnapCenterPS* para iniciar PowerShell Core.
. Cree una nueva conexión al sistema de almacenamiento mediante el cmdlet Add-SmStorageConnection.
+
[listing]
----
PS C:\> Add-SmStorageConnection -StorageType DataOntap -Type DataOntap -OntapStorage ‘scsnfssvm’ -Protocol Https -Timeout 60
----
. Cree una nueva credencial mediante el cmdlet Add-SmCredential.
+
Este ejemplo muestra cómo crear una nueva credencial llamada FinanceAdmin con credenciales de Windows:

+
[listing]
----
PS C:\> Add-SmCredential -Name 'FinanceAdmin' -Type Linux -AuthenticationType PasswordBased -Credential db2hostuser -EnableSudoPrevileges:$true
----
. Agregue el host de comunicación IBM Db2 al servidor SnapCenter .
+
Para Linux:

+
[listing]
----
PS C:\> Add-SmHost -HostType Linux -HostName '10.232.204.61' -CredentialName 'defaultcreds'
----
+
Para Windows:

+
[listing]
----
PS C:\> Add-SmHost -HostType Windows -HostName '10.232.204.61' -CredentialName 'defaultcreds'
----
. Instale el paquete y el complemento SnapCenter para IBM Db2 en el host.
+
Para Linux:

+
[listing]
----
PS C:\> Install-SmHostPackage -HostNames '10.232.204.61' -PluginCodes DB2
----
+
Para Windows:

+
[listing]
----
PS C:\> Install-SmHostPackage -HostNames '10.232.204.61' -PluginCodes DB2,SCW
----
. Establezca la ruta a SQLLIB.
+
Para Windows, el complemento Db2 utilizará la ruta predeterminada para la carpeta SQLLIB: “C:\Program Files\IBM\SQLLIB\BIN”

+
Si desea anular la ruta predeterminada, utilice el siguiente comando.

+
[listing]
----
PS C:\> Set-SmConfigSettings -Plugin -HostName '10.232.204.61' -PluginCode DB2 -configSettings @{"DB2_SQLLIB_CMD"="<custom_path>\IBM\SQLLIB\BIN"}

----


La información sobre los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help command_name_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets del software SnapCenter"^] .
