---
permalink: protect-db2/get-the-CA-certificate-thumbprint.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Obtenga la huella digital del certificado CA. 
---
= Obtenga la huella digital del certificado CA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una huella digital de certificado es una cadena hexadecimal que identifica un certificado.  La huella digital se calcula a partir del contenido del certificado utilizando un algoritmo de huella digital.

.Pasos
. Realice lo siguiente en la GUI:
+
.. Haga doble clic en el certificado.
.. En el cuadro de diálogo Certificado, haga clic en la pestaña *Detalles*.
.. Desplácese por la lista de campos y haga clic en *Huella digital*.
.. Copia los caracteres hexadecimales del cuadro.
.. Eliminar los espacios entre los números hexadecimales.
+
Por ejemplo, si la huella digital es: "a9 09 50 2d d8 2a e4 14 33 e6 f8 38 86 b0 0d 42 77 a3 2a 7b", después de eliminar los espacios, será: "a909502dd82ae41433e6f83886b00d4277a32a7b".



. Realice lo siguiente desde PowerShell:
+
.. Ejecute el siguiente comando para enumerar la huella digital del certificado instalado e identificar el certificado recientemente instalado por el nombre del sujeto.
+
_Get-ChildItem -Path Certificado:\LocalMachine\Mi_

.. Copiar la huella digital.



