---
permalink: protect-nsp/backup_schedules_of_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: NetApp supported plug-in 
summary: El factor más crítico para determinar un cronograma de respaldo es la tasa de cambio del recurso.  Cuanto más a menudo realice copias de seguridad de sus recursos, menos registros de archivo tendrá que utilizar SnapCenter para restaurar, lo que puede generar operaciones de restauración más rápidas. 
---
= Programaciones de respaldo de recursos de complementos compatibles con NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El factor más crítico para determinar un cronograma de respaldo es la tasa de cambio del recurso.  Cuanto más a menudo realice copias de seguridad de sus recursos, menos registros de archivo tendrá que utilizar SnapCenter para restaurar, lo que puede generar operaciones de restauración más rápidas.

Es posible que hagas una copia de seguridad de un recurso muy utilizado cada hora, mientras que es posible que hagas una copia de seguridad de un recurso poco utilizado una vez al día.  Otros factores incluyen la importancia del recurso para su organización, su acuerdo de nivel de servicio (SLA) y su objetivo de punto de recuperación (RPO).

SLA define el nivel de servicio esperado y aborda muchas cuestiones relacionadas con el servicio, incluida la disponibilidad y el rendimiento del servicio.  RPO define la estrategia para la edad de los archivos que deben recuperarse del almacenamiento de respaldo para que las operaciones normales se reanuden después de una falla.  SLA y RPO contribuyen a la estrategia de protección de datos.

Los programas de respaldo constan de dos partes, como se indica a continuación:

* Frecuencia de respaldo
+
La frecuencia de copia de seguridad (con qué frecuencia se deben realizar las copias de seguridad), también llamada tipo de programación para algunos complementos, es parte de una configuración de política.  Por ejemplo, puede configurar la frecuencia de la copia de seguridad como horaria, diaria, semanal o mensual.  Puede acceder a las políticas en la GUI de SnapCenter haciendo clic en *Configuración* > *Políticas*.

* Programaciones de copias de seguridad
+
Las programaciones de copias de seguridad (exactamente cuándo se deben realizar las copias de seguridad) son parte de la configuración de un recurso o de un grupo de recursos.  Por ejemplo, si tiene un grupo de recursos que tiene una política configurada para copias de seguridad semanales, puede configurar la programación para realizar copias de seguridad todos los jueves a las 10:00 p. m. Puede acceder a las programaciones del grupo de recursos en la GUI de SnapCenter haciendo clic en *Recursos*, luego seleccionando el complemento apropiado y haciendo clic en *Ver* > *Grupo de recursos*.


