---
permalink: protect-nsp/create_policies_for_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: create policies, NetApp supported plug-in 
summary: Antes de usar SnapCenter para realizar copias de seguridad de recursos específicos del complemento compatible con NetApp , debe crear una política de copia de seguridad para el recurso o grupo de recursos que desea respaldar. 
---
= Crear políticas para recursos de complementos compatibles con NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar SnapCenter para realizar copias de seguridad de recursos específicos del complemento compatible con NetApp , debe crear una política de copia de seguridad para el recurso o grupo de recursos que desea respaldar.

.Antes de empezar
* Deberías haber definido tu estrategia de backup.
+
Para obtener más detalles, consulte la información sobre cómo definir una estrategia de protección de datos para los complementos compatibles con NetApp .

* Deberías estar preparado para la protección de datos.
+
La preparación para la protección de datos incluye tareas como instalar SnapCenter, agregar hosts, crear conexiones al sistema de almacenamiento y agregar recursos.

* Las máquinas virtuales de almacenamiento (SVM) deben asignarse a usted para operaciones de espejo o bóveda.
+
El administrador de SnapCenter debe haberle asignado las SVM para los volúmenes de origen y destino si está replicando instantáneas a un espejo o bóveda.

* Deberías haber agregado manualmente los recursos que deseas proteger.


.Acerca de esta tarea
* Una política de copias de seguridad es un conjunto de reglas que rigen cómo administrar, programar y conservar las copias de seguridad.  Además, puede especificar configuraciones de replicación, scripts y aplicaciones.
* Especificar opciones en una política ahorra tiempo cuando desea reutilizar la política para otro grupo de recursos.
* SnapLock
+
** Si se selecciona la opción 'Conservar las copias de seguridad durante una cantidad específica de días', el período de retención de SnapLock debe ser menor o igual a los días de retención mencionados.
** Al especificar un período de bloqueo de instantáneas se evita la eliminación de las instantáneas hasta que expire el período de retención. Esto podría llevar a retener una cantidad mayor de instantáneas que la cantidad especificada en la política.
** Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de SnapLock Vault como parte de la restauración heredarán el tiempo de vencimiento de SnapLock Vault. El administrador de almacenamiento debe limpiar manualmente los clones después del tiempo de vencimiento de SnapLock .





NOTE: Las configuraciones principales de SnapLock se administran en la política de respaldo de SnapCenter y las configuraciones secundarias de SnapLock son administradas por ONTAP.

.Pasos
. En el panel de navegación izquierdo, haga clic en *Configuración*.
. En la página de Configuración, haga clic en *Políticas*.
. Haga clic en *Nuevo*.
. En la página Nombre, ingrese el nombre y los detalles de la política.
. En la página Tipo de política, realice lo siguiente:
+
.. Seleccione el tipo de almacenamiento.
.. En la sección Configuración de copia de seguridad personalizada, proporcione cualquier configuración de copia de seguridad específica que deba pasarse al complemento en formato de clave-valor.
+
Puede proporcionar varios valores clave para pasarlos al complemento.



. En la página Instantánea y replicación, realice los siguientes pasos:
+
.. Especifique el tipo de programación seleccionando *A pedido*, *Por hora*, *Diariamente*, *Semanalmente* o *Mensualmente*.
+

NOTE: Puede especificar la programación (fecha de inicio, fecha de finalización y frecuencia) para la operación de copia de seguridad al crear un grupo de recursos.  Esto le permite crear grupos de recursos que comparten la misma política y frecuencia de respaldo, pero le permite asignar diferentes programas de respaldo a cada política.

+

NOTE: Si lo ha programado para las 2:00 a. m., el cronograma no se activará durante el horario de verano (DST).

.. En la sección Configuración de instantáneas, especifique la configuración de retención para el tipo de copia de seguridad y el tipo de programación seleccionados en la página *Tipo de copia de seguridad*:
+
|===
| Si quieres... | Entonces... 


 a| 
Mantenga una cierta cantidad de instantáneas
 a| 
Seleccione *Copias para conservar* y luego especifique la cantidad de instantáneas que desea conservar.

Si el número de instantáneas excede el número especificado, las instantáneas se eliminan primero, comenzando por las copias más antiguas.


NOTE: Debe establecer el recuento de retención en 2 o más si planea habilitar la replicación de SnapVault .  Si establece el recuento de retención en 1, la operación de retención puede fallar porque la primera instantánea es la instantánea de referencia para la relación SnapVault hasta que se replique una instantánea más nueva en el destino.


NOTE: El valor máximo de retención es 1018. Las copias de seguridad fallarán si la retención se establece en un valor superior al que admite la versión subyacente de ONTAP .



 a| 
Conservar las instantáneas durante un número determinado de días
 a| 
Seleccione *Conservar copias durante* y, a continuación, especifique la cantidad de días durante los cuales desea conservar las instantáneas antes de eliminarlas.



 a| 
Período de bloqueo de copia de instantánea
 a| 
Seleccione *Período de bloqueo de copia de instantánea* y especifique días, meses o años.

El período de retención de SnapLock debe ser inferior a 100 años.

|===
.. Seleccione una etiqueta de política.
+

NOTE: Puede asignar etiquetas SnapMirror a instantáneas principales para replicación remota, lo que permite que las instantáneas principales descarguen la operación de replicación de instantáneas de SnapCenter a los sistemas secundarios de ONTAP . Esto se puede hacer sin habilitar la opción SnapMirror o SnapVault en la página de políticas.



. En la sección Seleccionar opciones de replicación secundaria, seleccione una o ambas de las siguientes opciones de replicación secundaria:
+
|===
| Para este campo... | Haz esto... 


 a| 
*Actualizar SnapMirror después de crear una copia de Snapshot local*
 a| 
Seleccione este campo para crear copias reflejadas de los conjuntos de copias de seguridad en otro volumen (replicación SnapMirror ).

Si la relación de protección en ONTAP es de tipo Mirror and Vault y selecciona solo esta opción, las instantáneas creadas en el servidor principal no se transferirán al destino, pero aparecerán en él.  Si se selecciona esta instantánea desde el destino para realizar una operación de restauración, se muestra el siguiente mensaje de error: La ubicación secundaria no está disponible para la copia de seguridad almacenada/duplicada seleccionada.

Durante la replicación secundaria, el tiempo de expiración de SnapLock carga el tiempo de expiración de SnapLock principal.

Al hacer clic en el botón *Actualizar* en la página Topología, se actualiza el tiempo de vencimiento de SnapLock primario y secundario que se recuperan de ONTAP.

Ver link:view_netapp_supported_plugins_resource_backups_and_clones_in_the_topology_page.html["Vea las copias de seguridad y clones relacionados con los recursos de complementos compatibles con NetApp en la página Topología"] .



 a| 
*Actualizar SnapVault después de crear una copia de instantánea local*
 a| 
Seleccione esta opción para realizar la replicación de copia de seguridad de disco a disco (copias de seguridad de SnapVault ).

Durante la replicación secundaria, el tiempo de expiración de SnapLock carga el tiempo de expiración de SnapLock principal.  Al hacer clic en el botón *Actualizar* en la página Topología, se actualiza el tiempo de vencimiento de SnapLock primario y secundario que se recuperan de ONTAP.

Cuando SnapLock está configurado solo en el secundario de ONTAP conocido como SnapLock Vault, al hacer clic en el botón *Actualizar* en la página Topología se actualiza el período de bloqueo en el secundario que se recupera de ONTAP.

Para obtener más información sobre SnapLock Vault, consulte Confirmar instantáneas en WORM en un destino de bóveda.

Ver link:view_netapp_supported_plugins_resource_backups_and_clones_in_the_topology_page.html["Vea las copias de seguridad y clones relacionados con los recursos de complementos compatibles con NetApp en la página Topología"] .



 a| 
*Recuento de reintentos por error*
 a| 
Introduzca el número máximo de intentos de replicación que se pueden permitir antes de que se detenga la operación.

|===
+

NOTE: Debe configurar la política de retención de SnapMirror en ONTAP para el almacenamiento secundario para evitar alcanzar el límite máximo de instantáneas en el almacenamiento secundario.

. Revise el resumen y luego haga clic en *Finalizar*.

