---
permalink: protect-nsp/netapp_supported_plugins_features.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins features, MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB, Storage plug-in 
summary: SnapCenter se integra con la aplicación complementaria y con las tecnologías NetApp en el sistema de almacenamiento.  Para trabajar con complementos compatibles con NetApp , utilice la interfaz gráfica de usuario de SnapCenter . 
---
= Funciones de los complementos compatibles con NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter se integra con la aplicación complementaria y con las tecnologías NetApp en el sistema de almacenamiento.  Para trabajar con complementos compatibles con NetApp , como MongoDB, ORASCPM (Aplicaciones Oracle), SAP ASE, SAP MaxDB y el complemento de almacenamiento, utilice la interfaz gráfica de usuario de SnapCenter .

* *Interfaz gráfica de usuario unificada*
+
La interfaz de SnapCenter proporciona estandarización y consistencia entre complementos y entornos.  La interfaz de SnapCenter le permite completar operaciones consistentes de respaldo, restauración, recuperación y clonación en todos los complementos, utilizar informes centralizados, usar vistas de panel de un vistazo, configurar el control de acceso basado en roles (RBAC) y monitorear trabajos en todos los complementos.

* *Administración central automatizada*
+
Puede programar operaciones de respaldo, configurar la retención de respaldo basada en políticas y realizar operaciones de restauración.  También puede supervisar su entorno de forma proactiva configurando SnapCenter para enviar alertas por correo electrónico.

* *Tecnología NetApp Snapshot sin interrupciones*
+
SnapCenter utiliza la tecnología NetApp Snapshot con los complementos compatibles con NetApp para realizar copias de seguridad de los recursos.  Las instantáneas consumen un espacio de almacenamiento mínimo.



Los complementos compatibles con NetApp también ofrecen los siguientes beneficios:

* Compatibilidad con flujos de trabajo de copia de seguridad, restauración y clonación
* Seguridad respaldada por RBAC y delegación de roles centralizada
+
También puede configurar las credenciales para que los usuarios autorizados de SnapCenter tengan permisos a nivel de aplicación.

* Creación de copias puntuales y con uso eficiente del espacio de recursos para pruebas o extracción de datos mediante la tecnología NetApp FlexClone
+
Se requiere una licencia FlexClone en el sistema de almacenamiento donde desea crear el clon.

* Compatibilidad con la función de instantánea del grupo de consistencia (CG) de ONTAP como parte de la creación de copias de seguridad.
* Capacidad de ejecutar múltiples copias de seguridad simultáneamente en múltiples hosts de recursos
+
En una sola operación, las instantáneas se consolidan cuando los recursos de un solo host comparten el mismo volumen.

* Capacidad de crear instantáneas mediante comandos externos.
* Capacidad para crear instantáneas consistentes con el sistema de archivos en entornos Windows.

