---
permalink: protect-nsp/set_up_credentials_for_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter utiliza credenciales para autenticar a los usuarios para las operaciones de SnapCenter .  Debe crear credenciales para instalar complementos de SnapCenter y credenciales adicionales para realizar operaciones de protección de datos en bases de datos o sistemas de archivos de Windows. 
---
= Configurar credenciales para complementos compatibles con NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utiliza credenciales para autenticar a los usuarios para las operaciones de SnapCenter .  Debe crear credenciales para instalar complementos de SnapCenter y credenciales adicionales para realizar operaciones de protección de datos en bases de datos o sistemas de archivos de Windows.

.Antes de empezar
* Hosts Linux o AIX
+
Debe configurar credenciales para instalar complementos en hosts Linux o AIX.

+
Debe configurar las credenciales para el usuario root o para un usuario no root que tenga privilegios de sudo para instalar e iniciar el proceso del complemento.

+
|===


| *Mejor práctica:* Si bien se le permite crear credenciales para Linux después de implementar hosts e instalar complementos, la mejor práctica es crear credenciales después de agregar SVM, antes de implementar hosts e instalar complementos. 
|===
* Hosts de Windows
+
Debe configurar las credenciales de Windows antes de instalar complementos.

+
Debe configurar las credenciales con privilegios de administrador, incluidos derechos de administrador en el host remoto.

* Aplicaciones de complementos compatibles con NetApp
+
El complemento utiliza las credenciales que se seleccionan o crean al agregar un recurso.  Si un recurso no requiere credenciales durante las operaciones de protección de datos, puede configurar las credenciales como *Ninguno*.



.Acerca de esta tarea
Si configura credenciales para grupos de recursos individuales y el nombre de usuario no tiene privilegios de administrador completos, debe asignar al menos los privilegios de grupo de recursos y de respaldo al nombre de usuario.

.Pasos
. En el panel de navegación izquierdo, haga clic en *Configuración*.
. En la página de Configuración, haga clic en *Credencial*.
. Haga clic en *Nuevo*.
. En la página *Credenciales*, especifique la información necesaria para configurar las credenciales:
+
|===
| Para este campo... | Haz esto... 


 a| 
Nombre de la credencial
 a| 
Introduzca un nombre para las credenciales.



 a| 
Nombre de usuario
 a| 
Introduzca el nombre de usuario y la contraseña que se utilizarán para la autenticación.

** Administrador del dominio o cualquier miembro del grupo de administradores
+
Especifique el administrador del dominio o cualquier miembro del grupo de administradores del sistema donde va a instalar el complemento de SnapCenter . Los formatos válidos para el campo Nombre de usuario son:

+
*** _NetBIOS\Nombre de usuario_
*** _Dominio FQDN\Nombre de usuario_


** Administrador local (sólo para grupos de trabajo)
+
Para los sistemas que pertenecen a un grupo de trabajo, especifique el administrador local integrado en el sistema donde va a instalar el complemento de SnapCenter . Puede especificar una cuenta de usuario local que pertenezca al grupo de administradores locales si esta cuenta tiene privilegios elevados o si la función de control de acceso de usuario está deshabilitada en el sistema host.  El formato válido para el campo Nombre de usuario es: _NombreDeUsuario_





 a| 
Password
 a| 
Introduzca la contraseña utilizada para la autenticación.



 a| 
Tipo de autenticación
 a| 
Seleccione el tipo de autenticación que desea utilizar.



 a| 
Utilice privilegios de sudo
 a| 
Seleccione la casilla de verificación *Usar privilegios de sudo* si está creando credenciales para un usuario que no sea root.


NOTE: Aplicable únicamente a usuarios de Linux y AIX.

|===
. Haga clic en *Aceptar*.


Una vez que termine de configurar las credenciales, es posible que desee asignar el mantenimiento de credenciales a un usuario o grupo de usuarios en la página Usuario y acceso.
