---
permalink: protect-nsp/storage_types_supported_by_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins 
summary: SnapCenter admite una amplia gama de tipos de almacenamiento en máquinas físicas y virtuales.  Debe verificar la compatibilidad con su tipo de almacenamiento antes de instalar complementos compatibles con NetApp . 
---
= Tipos de almacenamiento compatibles con los complementos de NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter admite una amplia gama de tipos de almacenamiento en máquinas físicas y virtuales.  Debe verificar la compatibilidad con su tipo de almacenamiento antes de instalar complementos compatibles con NetApp .

|===
| Máquina | Tipo de almacenamiento 


 a| 
Montajes directos físicos y NFS en los hosts de VM (no se admiten VMDK ni LUN RDM).
 a| 
LUN conectados a FC



 a| 
Montajes directos físicos y NFS en los hosts de VM (no se admiten VMDK ni LUN RDM).
 a| 
LUN conectados a iSCSI



 a| 
Montajes directos físicos y NFS en los hosts de VM (no se admiten VMDK ni LUN RDM).
 a| 
Volúmenes conectados a NFS



 a| 
VMware ESXi
 a| 
Almacenes de datos vVol tanto en NFS como en SAN

El almacén de datos vVol solo se puede aprovisionar con ONTAP Tools para VMware vSphere.

|===