---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: Las credenciales utilizan diferentes métodos de autenticación según la aplicación o el entorno.  Las credenciales autentican a los usuarios para que puedan realizar operaciones de SnapCenter .  Debe crear un conjunto de credenciales para instalar complementos y otro conjunto para operaciones de protección de datos. 
---
= Métodos de autenticación para las credenciales de SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las credenciales utilizan diferentes métodos de autenticación según la aplicación o el entorno.  Las credenciales autentican a los usuarios para que puedan realizar operaciones de SnapCenter .  Debe crear un conjunto de credenciales para instalar complementos y otro para las operaciones de protección de datos.



== Autenticación de Windows

El método de autenticación de Windows se autentica contra Active Directory.  Para la autenticación de Windows, Active Directory se configura fuera de SnapCenter.  SnapCenter se autentica sin configuración adicional.  Necesita una credencial de Windows para agregar hosts, instalar paquetes de complementos y programar trabajos.



== Autenticación de dominio no confiable

SnapCenter permite que los usuarios y grupos que pertenecen a dominios no confiables creen credenciales de Windows.  Para que la autenticación sea exitosa, debes registrar los dominios no confiables con SnapCenter.



== Autenticación de grupo de trabajo local

SnapCenter permite la creación de credenciales de Windows con usuarios y grupos de trabajo locales.  La autenticación de Windows para usuarios y grupos de grupos de trabajo locales no ocurre durante la creación de credenciales de Windows, sino que se pospone hasta que se realizan el registro del host y otras operaciones del host.



== Autenticación de SQL Server

El método de autenticación SQL se autentica contra una instancia de SQL Server.  Esto significa que se debe descubrir una instancia de SQL Server en SnapCenter.  Por lo tanto, antes de agregar una credencial SQL, debe agregar un host, instalar paquetes de complementos y actualizar los recursos.  Necesita la autenticación de SQL Server para realizar operaciones como programar en SQL Server o descubrir recursos.



== Autenticación de Linux

El método de autenticación de Linux se autentica contra un host Linux.  Necesita autenticación de Linux durante el paso inicial de agregar el host Linux e instalar el paquete de complementos de SnapCenter para Linux de forma remota desde la GUI de SnapCenter .



== Autenticación AIX

El método de autenticación AIX se autentica contra un host AIX.  Necesita autenticación AIX durante el paso inicial de agregar el host AIX e instalar el paquete de complementos de SnapCenter para AIX de forma remota desde la GUI de SnapCenter .



== Autenticación de base de datos de Oracle

El método de autenticación de base de datos de Oracle se autentica contra una base de datos de Oracle.  Necesita una autenticación de base de datos Oracle para realizar operaciones en la base de datos Oracle si la autenticación del sistema operativo (SO) está deshabilitada en el host de la base de datos.  Por lo tanto, antes de agregar una credencial de base de datos Oracle, debe crear un usuario Oracle en la base de datos Oracle con privilegios sysdba.



== Autenticación de Oracle ASM

El método de autenticación de Oracle ASM se autentica contra una instancia de Oracle Automatic Storage Management (ASM).  Se requiere autenticación de Oracle ASM si necesita acceder a una instancia de Oracle ASM y la autenticación del sistema operativo está deshabilitada en el host de la base de datos.  Antes de agregar una credencial de Oracle ASM, cree un usuario de Oracle con privilegios de sistema en la instancia de ASM.



== Autenticación del catálogo RMAN

El método de autenticación del catálogo RMAN se autentica contra la base de datos del catálogo de Oracle Recovery Manager (RMAN).  Si ha configurado un mecanismo de catálogo externo y ha registrado su base de datos en la base de datos del catálogo, debe agregar la autenticación del catálogo RMAN.
