---
permalink: get-started/concept_snapcenter_licenses.html 
sidebar: sidebar 
keywords: licenses, FAS, AFF, ASA, SnapMirror, SnapVault, SnapRestore, FlexClone, SMBR, Single Mailbox Recovery 
summary: SnapCenter requiere varias licencias para habilitar operaciones de protección de datos. El tipo de licencias de SnapCenter que instale dependerá de su entorno de almacenamiento y de las funciones que desee utilizar. 
---
= Licencias requeridas por SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter requiere varias licencias para habilitar la protección de datos de aplicaciones, bases de datos, sistemas de archivos y máquinas virtuales. El tipo de licencias de SnapCenter que instale dependerá de su entorno de almacenamiento y de las funciones que desee utilizar.

|===
| Licencia | Cuando sea necesario 


 a| 
SnapCenter Standard basado en controlador
 a| 
Requerido para FAS, AFF, ASA

La licencia estándar de SnapCenter es una licencia basada en controlador y se incluye como parte de NetApp ONTAP One.  Si tiene la licencia de SnapManager Suite, también obtendrá el derecho de licencia de SnapCenter Standard.  Si desea instalar SnapCenter a modo de prueba con almacenamiento FAS, AFF o ASA , puede obtener una licencia de evaluación de NetApp ONTAP One comunicándose con el representante de ventas.

Para obtener información sobre las licencias incluidas con NetApp ONTAP One, consulte https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licencias incluidas con NetApp ONTAP One"] .


NOTE: SnapCenter también se ofrece como parte del paquete de protección de datos.  Si ha adquirido el modelo A400 o posterior, deberá adquirir el paquete de protección de datos.



 a| 
SnapMirror o SnapVault
 a| 
ONTAP

Se requiere una licencia de SnapMirror o SnapVault si la replicación está habilitada en SnapCenter.



 a| 
SnapRestore
 a| 
Necesario para restaurar y verificar copias de seguridad.

Sobre los sistemas de almacenamiento primario

* Requerido en los sistemas de destino SnapVault para realizar la verificación remota y restaurar desde una copia de seguridad.
* Requerido en los sistemas de destino SnapMirror para realizar la verificación remota.




 a| 
FlexClone
 a| 
Necesario para clonar bases de datos y realizar operaciones de verificación.

Sobre sistemas de almacenamiento primario y secundario

* Requerido en los sistemas de destino SnapVault para crear clones a partir de una copia de seguridad de la bóveda secundaria.
* Requerido en los sistemas de destino SnapMirror para crear clones a partir de una copia de seguridad secundaria de SnapMirror .




 a| 
Licencias de protocolo
 a| 
* Licencia iSCSI o FC para LUN
* Licencia CIFS para acciones SMB
* Licencia NFS para VMDK de tipo NFS
* Licencia iSCSI o FC para VMDK de tipo VMFS


Obligatorio en los sistemas de destino SnapMirror para servir datos si un volumen de origen no está disponible.



 a| 
Licencias estándar de SnapCenter (opcionales)
 a| 
Destinos secundarios


NOTE: Se recomienda, aunque no es obligatorio, que agregue licencias estándar de SnapCenter a destinos secundarios.  Si las licencias estándar de SnapCenter no están habilitadas en destinos secundarios, no podrá usar SnapCenter para realizar copias de seguridad de recursos en el destino secundario después de realizar una operación de conmutación por error.  Sin embargo, se requiere una licencia FlexClone en destinos secundarios para realizar operaciones de clonación y verificación.



 a| 
Licencias de recuperación de buzón único (SMBR)
 a| 
Si utiliza el complemento SnapCenter para Exchange para administrar las bases de datos de Microsoft Exchange Server y Single Mailbox Recovery (SMBR), necesitará una licencia adicional para SMBR que debe comprarse por separado según el buzón del usuario.

NetApp® Single Mailbox Recovery llegó al final de su disponibilidad (EOA) el 12 de mayo de 2023.  Para obtener más información, consultelink:https://mysupport.netapp.com/info/communications/ECMLP2885729.html["CPC-00507"] .  NetApp seguirá brindando soporte a los clientes que hayan adquirido capacidad de buzón, mantenimiento y soporte a través de los números de pieza de marketing introducidos el 24 de junio de 2020, mientras dure el derecho de soporte.

NetApp Single Mailbox Recovery es un producto asociado proporcionado por Ontrack.  Ontrack PowerControls ofrece capacidades similares a las de NetApp Single Mailbox Recovery.  Los clientes pueden adquirir nuevas licencias de software Ontrack PowerControls y renovaciones de mantenimiento y soporte de Ontrack PowerControls de Ontrack (a través de licensingteam@ontrack.com) para la recuperación granular del buzón después de la fecha de fin de operación del 12 de mayo de 2023.

|===

NOTE: Las licencias de SnapCenter Advanced y SnapCenter NAS File Services están obsoletas y ya no están disponibles.  La licencia estándar y la licencia basada en capacidad ya no son necesarias para Amazon FSx for NetApp ONTAP, ONTAP Select, Cloud Volumes ONTAP y Azure NetApp Files.

Debe instalar una o más licencias de SnapCenter .  Para obtener información sobre cómo agregar licencias, consultelink:../install/concept_snapcenter_standard_controller_based_licenses.html["Agregar licencias basadas en controlador de SnapCenter Standard"] .
