---
permalink: get-started/reference_data_security.html 
sidebar: sidebar 
keywords: security, authentication, CA certificates, FIPS, SSL, AES, TLS, RBAC, MFA, multi-factor authentication 
summary: SnapCenter emplea estrictas funciones de seguridad y autenticación para permitirle mantener sus datos seguros. 
---
= Funciones de seguridad en SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter emplea estrictas funciones de seguridad y autenticación para permitirle mantener sus datos seguros.

SnapCenter incluye las siguientes funciones de seguridad:

* Toda comunicación con SnapCenter utiliza HTTP sobre SSL (HTTPS).
* Todas las credenciales en SnapCenter están protegidas mediante el cifrado Estándar de cifrado avanzado (AES).
* Admite algoritmos de seguridad que cumplen con el Estándar Federal de Procesamiento de Información (FIPS).
* Admite el uso de los certificados CA autorizados proporcionados por el cliente.
* Admite seguridad de la capa de transporte (TLS) 1.3 para la comunicación con ONTAP.  También puede utilizar TLS 1.2 para la comunicación entre clientes y servidores.
* Admite un determinado conjunto de suites de cifrado SSL para proporcionar seguridad en las comunicaciones de red. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_the_supported_SSL_Cipher_Suite["Más información"] .
* SnapCenter se instala dentro del firewall de su empresa para permitir el acceso al servidor SnapCenter y para permitir la comunicación entre el servidor SnapCenter y los complementos.
* El acceso a la API y a las operaciones de SnapCenter utiliza tokens cifrados con cifrado AES, que caducan después de 24 horas.
* SnapCenter se integra con Windows Active Directory para el inicio de sesión y el control de acceso basado en roles (RBAC) que rigen los permisos de acceso.
* IPsec es compatible con SnapCenter en ONTAP para máquinas host de Windows y Linux. https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html#use-ipsec-identities["Más información"] .
* Los cmdlets de PowerShell de SnapCenter están protegidos por sesión.
* Después de un período predeterminado de 15 minutos de inactividad, SnapCenter le advierte que se cerrará su sesión en 5 minutos.
+
Después de 20 minutos de inactividad, SnapCenter cerrará su sesión y deberá iniciar sesión nuevamente.  Puede modificar el período de cierre de sesión.

* El inicio de sesión se deshabilita temporalmente después de 5 intentos de inicio de sesión incorrectos.
* Admite la autenticación de certificados CA entre SnapCenter Server y ONTAP. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_securely_connect_SnapCenter_with_ONTAP_using_CA_certificate["Más información"] .
* Integrity Verifier se agrega al servidor SnapCenter y a los complementos y valida todos los binarios enviados durante las operaciones de instalación y actualización nuevas.




== Descripción general del certificado CA

El instalador de SnapCenter Server habilita la compatibilidad con certificados SSL centralizados durante la instalación.  Para mejorar la comunicación segura entre el servidor y el complemento, SnapCenter admite el uso de los certificados CA autorizados proporcionados por el cliente.

Debe implementar certificados CA después de instalar SnapCenter Server y los complementos respectivos. Para obtener más información, consulte link:../install/reference_generate_CA_certificate_CSR_file.html["Generar archivo CSR de certificado de CA"] .

También puede implementar un certificado CA para el complemento SnapCenter para VMware vSphere. Para obtener más información, consulte  https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_and_import_certificates.html["Crear e importar certificados"^] .



== Comunicación SSL bidireccional

La comunicación SSL bidireccional asegura la comunicación mutua entre SnapCenter Server y los complementos.



== Descripción general de la autenticación basada en certificados

La autenticación basada en certificados verifica la autenticidad de los respectivos usuarios que intentan acceder al host del complemento SnapCenter .  El usuario debe exportar el certificado del servidor SnapCenter sin clave privada e importarlo en el almacén de confianza del host del complemento.  La autenticación basada en certificado solo funciona si la función SSL bidireccional está habilitada.



== Autenticación multifactor (MFA)

MFA utiliza un proveedor de identidad (IdP) de terceros a través del lenguaje de marcado de aserción de seguridad (SAML) para administrar las sesiones de usuario.  Esta funcionalidad mejora la seguridad de la autenticación al tener la opción de utilizar múltiples factores como TOTP, biometría, notificaciones push, etc. junto con el nombre de usuario y la contraseña existentes.  Además, permite al cliente utilizar sus propios proveedores de identidad de usuario para obtener un inicio de sesión de usuario unificado (SSO) en toda su cartera.

MFA solo se aplica para iniciar sesión en la interfaz de usuario de SnapCenter Server.  Los inicios de sesión se autentican a través del IdP Servicios de federación de Active Directory (AD FS).  Puede configurar varios factores de autenticación en AD FS.  SnapCenter es el proveedor de servicios y debe SnapCenter como parte confiable en AD FS.  Para habilitar MFA en SnapCenter, necesitará los metadatos de AD FS.

Para obtener información sobre cómo habilitar MFA, consultelink:../install/enable_multifactor_authentication.html["Habilitar la autenticación multifactor"] .
