---
permalink: uninstall/task_uninstalling_windows_plug_ins_using_the_command_line_interface_on_the_snapcenter_server_host.html 
sidebar: sidebar 
keywords: uninstall, windows plug-ins, powershell cmdlet 
summary: Puede desinstalar complementos individuales o desinstalar paquetes de complementos de uno o más hosts mediante el cmdlet Uninstall-SmHostPackage en la interfaz de línea de comandos del host de SnapCenter Server. 
---
= Desinstalar complementos de Windows mediante el cmdlet de PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desinstalar complementos individuales o desinstalar paquetes de complementos de uno o más hosts mediante el cmdlet _Uninstall-SmHostPackage_ en la interfaz de línea de comandos del host de SnapCenter Server.

Debería haber iniciado sesión en SnapCenter como un usuario de dominio con derechos de administrador local en cada host en el que desee desinstalar los complementos.

.Pasos
. Inicie PowerShell.
. En el host del servidor SnapCenter , ingrese el comando _Open-SMConnection -SMSbaseUrl \https://SNAPCENTER_SERVER_NAME/DOMAIN_NAME_ y luego ingrese sus credenciales.
. Desinstale los complementos de Windows mediante el cmdlet _Uninstall-SmHostPackage_ y los parámetros necesarios.
+
La información sobre los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help command_name_.  Alternativamente, también puede consultar el https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets del software SnapCenter"^] .


