---
permalink: protect-mysql/snapcenter-plug-in-for-mysql-overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: El complemento SnapCenter para MySQL es un componente del lado del host del SnapCenter software de NetApp que permite la gestión de protección de datos consciente de la aplicación de las bases de datos MySQL.  El complemento para la base de datos MySQL automatiza la copia de seguridad, la restauración y la clonación de bases de datos MySQL en su entorno de SnapCenter . 
---
= Descripción general del complemento SnapCenter para MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El complemento SnapCenter para bases de datos MySQL es un componente del lado del host del SnapCenter software de NetApp que permite la gestión de protección de datos consciente de la aplicación de bases de datos MySQL.  El complemento para la base de datos MySQL automatiza la copia de seguridad, la restauración y la clonación de bases de datos MySQL en su entorno de SnapCenter .

SnapCenter admite configuraciones de MySQL de instancia única.  Puede utilizar el complemento para la base de datos MySQL en entornos Linux y Windows.  En entornos Windows, MySQL se soportará como recurso manual.

Cuando se instala el complemento para la base de datos MySQL, puede utilizar SnapCenter con la tecnología NetApp SnapMirror para crear copias reflejadas de conjuntos de copias de seguridad en otro volumen.  También puede utilizar el complemento con la tecnología NetApp SnapVault para realizar la replicación de copias de seguridad de disco a disco para el cumplimiento de los estándares.

El complemento SnapCenter para MySQL admite NFS y SAN en diseños de almacenamiento de archivos ONTAP y Azure NetApp .

Se admite el diseño de almacenamiento virtual VMDK, vVol y RDM.

No se admiten enlaces simbólicos.
